<div class="row">
    <?php echo $this->partial('agentes/inc/menu.inc.php', $this) ?>
    <div class="col s10">
        <script type="text/javascript">
            function enviarform() {
                if (validaEndereco()) {
                    $("#logradouro").attr("disabled", "");
                    $("#tipoLogradouro").attr("disabled", "");
                    $("#bairro").attr("disabled", "");
                    $("#cidade").attr("disabled", "");
                    $("#uf").attr("disabled", "");

                    $("#form").submit();
                }
            }

            function buscarcep(cep) {
                // pega os dados a serem populados
                var logradouro = document.getElementById("logradouro");
                var tipoLogradouro = document.getElementById("tipoLogradouro");
                var bairro = document.getElementById("bairro");
                var cidade = document.getElementById("cidade");
                var uf = document.getElementById("uf");
                var url = "<?php echo $this->url(array('module' => 'default', 'controller' => 'cep', 'action' => 'cep')); ?>?cep=" + cep;

                $('#erroCep').html("");
                if (cep.length != 10) {
                    $('#erroCep').html("O CEP informado &eacute; inv&aacute;lido!");
                    $("#logradouro, #bairro").val(' ');
                    $("#cidade option[value=0]").html(" - Selecione - ");
                    $("#uf option[value=0]").html(" - Selecione - ");
                    $("#tipoLogradouro option[value=0]").html(" - Selecione - ");
                    return false;
                }
                if (cep.length == 10) {

                    $.ajax({
                        url: url,
                        dataType: "json",
                        beforeSend: function () {

                            $(document).ajaxStart(function () {
                                $('#container-progress').fadeIn('slow');
                            });
                            $(document).ajaxComplete(function () {
                                $('#container-progress').fadeOut('slow');
                            });

                            $("#logradouro").attr("disabled", 'disabled');
                            $("#bairro").attr("disabled", 'disabled');

                            $("#logradouro").val("carregando...");
                            $("#bairro").val("carregando...");
                            $("#cidade option[value=0]").html("Carregando...");
                            $("#uf option[value=0]").html("Carregando...");

                            $3('select').material_select('destroy');
                            $3('select').material_select();

                            $('#erroCep').html("<img src='/public/img/ajax.gif' alt='' /> Aguarde...");
                        },
                        success: function (data) {
                            $('#erroCep').html("");
                            $('#logradouro').val(data.logradouro);
                            $('#complemento').val(data.complemento);
                            $('#bairro').val(data.bairro);
//                        $('#cidade > select > option[value="' + data.cidade + '"]').attr("selected", "selected");
                            $("#cidade option[value=0]").html(data.cidade).val(data.cod_cidade);
                            $("#uf option[value=0]").html(data.uf);

                            $3('select').material_select('destroy');
                            $3('select').material_select();

                            if (data.cidade == "") {
                                carregar_combo($("#uf").val(), 'cidade', '/cidade/combo', ' - Selecione - ');
                            }
                        }
                    });
                }
            }

            $(document).ready(function () {
                    $3('select').material_select();
                }
            );

        </script>

        <div id="breadcrumb">
            <ul>
                <li class="first"><a
                        href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>"
                        title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
                <li><a href="#" title="Tramita&ccedil;&atilde;o de Documentos">Manter Agentes</a></li>
                <li class="last">Principal</li>
            </ul>
        </div>

        <div id="titulo">
            <div>Endere&ccedil;os <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
        </div>
        <div id="conteudo">
            <?php echo $this->partial('agentes/inc/cabecalho.php', $this) ?>
            <table class="tabela">
                <tr>
                    <td>Para adicionar um novo endere&ccedil;o, clique em novo ao lado!</td>
                    <th width="150"><input type="button" class="btn_novo" value=" " onclick="novo();"/></th>
                </tr>
            </table>
            <div id="formNovo" class="sumir">
                <!-- ========== INICIO FORMULARIO ENDERECO ========== -->
                <form id="form" name="form"
                      action="<?php echo $this->url(array('module' => 'agente', 'controller' => 'agentes', 'action' => 'salvaendereco')); ?>"
                      method="post">
                    <table id="tabEndereco" class="tabela">
                        <tr>
                            <th colspan="3">Novo Endere&ccedil;o</th>
                        </tr>
                        <tr>
                            <td>
                                <label for="cep">CEP *</label><br/>
                                <input class="input_simples" type="text" name="cep" id="cep" maxlength="10"
                                       onkeyup="mascara(this, format_cep);" onblur="buscarcep(this.value);"
                                       onclick="limpar_campo(this, '');" onkeypress="limpar_campo(this, '');"
                                       onblur="restaurar_campo(this, '');" onmouseout="restaurar_campo(this, '');"
                                       value=" "/>

                                &nbsp; <span id="erroCep" class="spanError"></span>
                            </td>
                            <td>
                                <label for="uf">UF *</label> <br/>
                                <select name="uf" id="uf" class="" disabled="disabled"
                                        onchange="carregar_combo(this.value,'cidade','<?php echo $this->url(array('module' => 'default', 'controller' => 'cidade', 'action' => 'combo')); ?>',' - Selecione primeiro o UF - ');">

                                    <?php if (!isset($this->uf) || empty($this->uf)) { ?>
                                        <option value="0"> --</option>
                                    <?php } ?>

                                    <?php foreach ($this->comboestados as $key => $comboestado): ?>
                                        <option value="<?php echo $key; ?>"
                                            <?php if ($this->uf == $key) echo "selected=\"selected\""; ?> >
                                            <?php echo $comboestado; ?>
                                        </option>
                                    <?php endforeach; ?>

                                </select>
                                <span id="erroUf" class="spanError"></span>
                            </td>
                            <td>
                                <label for="cidade">Cidade *</label> <br/>
                                <select name="cidade" id="cidade" disabled="disabled" class="">
                                    <option value="0"> - Selecione -</option>
                                    <?php if ($this->combocidades) : ?>
                                        <?php foreach ($this->combocidades as $key => $combocidade): ?>
                                            <option value="<?php echo $key; ?>"
                                                    id="<?php echo $key; ?>"
                                                <?php if ($this->cidade == $key) echo "selected=\"selected\""; ?>>
                                                <?php echo $combocidade; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>

                                </select>
                                <span id="erroCidade" class="spanError"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="tipoEndereco">Tipo de Endere&ccedil;o *</label> <br/>
                                <select name="tipoEndereco" id="tipoEndereco" class="">

                                    <?php if (!isset($this->tipoEndereco) || empty($this->tipoEndereco)) { ?>
                                        <option value="0"> - Selecione -</option>
                                    <?php } ?>

                                    <?php foreach ($this->combotiposenderecos as $key => $combotipoendereco): ?>
                                        <option value="<?php echo $key; ?>"
                                            <?php if ($this->tipoEndereco == $key) echo "selected=\"selected\""; ?>>
                                            <?php echo $combotipoendereco; ?>
                                        </option>
                                    <?php endforeach; ?>

                                </select>
                                <span id="erroTipoEndereco" class="spanError"></span>
                            </td>
                            <td>
                                <label for="tipoLogradouro">Tipo de Logradouro *</label> <br/>
                                <select name="tipoLogradouro" id="tipoLogradouro" class="">

                                    <?php if (!isset($this->tipoLogradouro) || empty($this->tipoLogradouro)) { ?>
                                        <option value="0"> - Selecione -</option>
                                    <?php } ?>

                                    <?php foreach ($this->combotiposlogradouros as $key => $comboTipoLogradouro): ?>
                                        <option value="<?php echo $key; ?>"
                                            <?php if ($this->tipoLogradouro == $key) echo "selected=\"selected\""; ?>>
                                            <?php echo $comboTipoLogradouro; ?>
                                        </option>
                                    <?php endforeach; ?>

                                </select>
                                <span id="erroTipoLogradouro" class="spanError"></span>
                            </td>
                            <td>
                                <label for="logradouro">Logradouro *</label> <br/>
                                <input class="input_simples" type="text" name="logradouro" disabled="disabled"
                                       id="logradouro" maxlength="50" size="50"/>
                                <span id="erroLogradouro" class="spanError"></span>
                            </td>
                        </tr>
                        <tr>

                            <td>
                                <label for="numero">N&uacute;mero *</label> <br/>
                                <input class="input_simples" type="text" name="numero" id="numero" maxlength="10"
                                       size="30"/>
                                <span id="erroNumero" class="spanError"></span>
                            </td>
                            <td>
                                <label for="complemento">Complemento</label> <br/>
                                <input class="input_simples" type="text" name="complemento" id="complemento"
                                       maxlength="70"/>
                                <span id="erroComplemento" class="spanError"></span>
                            </td>
                            <td colspan="2">
                                <label for="bairro">Bairro *</label> <br/>
                                <input class="input_simples" type="text" disabled="disabled" name="bairro" id="bairro"
                                       maxlength="70"/>
                                <span id="erroBairro" class="spanError"></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Autorizo divulgar o endere&ccedil;o:</label>
                                <p>
                                    <input type="radio" name="divulgarEndereco" id="divulgarEnderecoS" value="1"
                                        class="checkradio"
                                        style="border: 0; float:none; clear:auto; display:inline;"/>
                                    <label for="divulgarFoneS">Sim</label>
                                    <br />
                                    <input type="radio" name="divulgarEndereco" id="divulgarEnderecoN" value="0"
                                        class="checkradio" checked="checked"
                                        style="border: 0; float:none; clear:auto; display:inline;"/>
                                    <label for="divulgarFoneN">N&atilde;o</label>
                                </p>
                            </td>
                            <td colspan="2">
                                <label>Endere&ccedil;o para correspod&ecirc;ncia?</label>
                                <p>
                                    <input type="radio" name="enderecoCorrespodencia" id="enderecoCorrespodenciaS" value="1"
                                        class="checkradio"
                                        style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                                    <label for="divulgarFoneS">Sim</label>
                                    <br />
                                    <input type="radio" name="enderecoCorrespodencia" id="enderecoCorrespodenciaN" value="0"
                                        class="checkradio" checked="checked"
                                        style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                                    <label for="divulgarFoneN">N&atilde;o</label>
                                </p>
                            </td>
                        </tr>
                    </table>

                    <!-- ========== FIM FORMULARIO ENDERECO ========== -->

                    <table class="tabela">
                        <tr>
                            <td class="centro">

                                <input type="button" class="btn_salvar" value=" " onclick="enviarform();"/> &nbsp;
                                <input id="btncancelar" type="button" class="btn_cancelar" onclick="salvo();"/>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
            <div id="salvos">
                <?php foreach ($this->endereco as $end): ?>
                    <table id="tabEndereco" class="tabela">
                        <tr>
                            <th colspan="5">ENDERE&Ccedil;OS</th>
                        </tr>
                        <tr>
                            <td><label>CEP:</label> <?php echo Mascara::addMaskCep($end->Cep); ?></td>
                            <td><label>UF:</label> <?php echo $end->uf; ?></td>
                            <td><label>Cidade:</label> <?php echo $end->municipio; ?></td>
                        </tr>
                        <tr>
                            <td colspan="2"><label>Tipo de Endere&ccedil;o:</label> <?php echo $end->TipoEndereco; ?>
                            </td>
                            <td><label>Tipo de Logradouro:</label> <?php echo $end->dsTipoLogradouro; ?></td>
                        </tr>
                        <tr>
                            <td colspan="2"><label>Logradouro:</label> <?php echo $end->Logradouro; ?></td>
                            <td><label>N&uacute;mero:</label> <?php echo $end->Numero; ?></td>
                        </tr>
                        <tr>
                            <td colspan="2"><label>Complemento:</label> <?php echo $end->Complemento; ?></td>
                            <td><label>Bairro:</label> <?php echo $end->Bairro; ?></td>
                        </tr>
                        <tr>
                            <td><label>Endere&ccedil;o para
                                    correspond&ecirc;ncia:</label> <?php echo $end->Status == "1" ? "SIM" : "N&Atilde;O"; ?>
                            </td>
                            <td colspan="2"><label>Autorizo divulgar o endere&ccedil;o:</label> 
                                <?php echo $end->Divulgar == "1" ? "SIM" : "N&Atilde;O"; ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" width="120" class="centro"><input type="button" class="btn_exclusao"
                                                                              value=" " style="width: 87px;"
                                                                              onclick="confirmaExclusao('', '<?php echo $this->url(array('module' => 'agente', 'controller' => 'agentes', 'action' => 'excluiendereco', 'idEndereco' => $end->idEndereco, 'qtdEndereco' => $this->qtdEndereco, 'enderecoCorrespondencia' => $end->Status)); ?>');"/>
                            </td>
                        </tr>
                    </table>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
