<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/agentes.js"></script>

<script type="text/javascript">


    function filtroCPF() {
        document.getElementById('0').checked = true;
        document.getElementById('1').checked = false;

        document.getElementById('cpf').value = "";
        document.getElementById('cpf').maxLength = "14";
        document.getElementById('cpf').onkeyup = function () {
            mascara(document.formCadAgentes.cpf, format_cpf);
        };
        document.getElementById('cpf').focus();
        $('#cadDirigente').hide(); // oculta a aba com os dirigentes


    }

    function filtroCNPJ() {
        document.getElementById('0').checked = false;
        document.getElementById('1').checked = true;

        document.getElementById('cpf').value = "";
        document.getElementById('cpf').maxLength = "18";
        document.getElementById('cpf').onkeyup = function () {
            mascara(document.formCadAgentes.cpf, format_cnpj);
        };
        document.getElementById('cpf').focus();
        $('#cadDirigente').show(); // mostra a aba com os dirigentes

        visao = document.getElementById("Visao");
        for (i = 1; i < visao.length; i++) // varre todo o option de origem
        {
            visao.remove(i); // remove os options
            i--;
        }

        // adiciona a vis&atilde;o de proponente
        var novoOption = document.createElement("option"); // cria um novo option
        novoOption.text = "Proponente"; // texto do option
        novoOption.value = 144; // valor do option
        visao.options.add(novoOption); // adiciona o novo option no select
    }


    function buscaragente(cpf) {
        $('#erroCpf').html('Aguarde!');

        Tipo = "";
        for (i = 0; i < document.formCadAgentes.Tipo.length; i++) {
            if (document.formCadAgentes.Tipo[i].checked) {
                Tipo = document.formCadAgentes.Tipo[i].value;
            }
        }

        value = $("#cpf").val();

        if (value == '') {
            $('#erroCpf').html('Informe o CPF/CNPJ!');
        }
        else if (Tipo == 0 && value.length != 14) {
            $('#erroCpf').html('CPF Incompleto!');
        }
        else if (Tipo == 1 && value.length != 18) {
            $('#erroCpf').html('CNPJ Incompleto!');
        }
        else if (Tipo == 0 && value.length != 14) {
            $('#erroCpf').html('CPF inv&aacute;lido!');
        }
        else if (Tipo == 1 && value.length != 18) {
            $('#erroCpf').html('CNPJ inv&aacute;lido!');
        }
        else {
            $('#erroCpf').html('');
            // retira as m&aacute;scaras do cpf/cnpj
            value = value.replace(".", "");
            value = value.replace(".", "");
            value = value.replace("/", "");
            cpf = value.replace("-", "");

            // faz a verifica&ccedil;&atilde;o do agente via post
            $.ajax({
                type: "POST",
                dataType: 'json',
                data: {
                    cpf: cpf
                },
                url: '<?php echo $this->url(array("controller" => "agentes", "action" => "agentecadastrado")); ?>',

                success: function (data) {
                    if (data[0].msgCPF == 'cadastrado') {
                        $('#novocadastro').hide();
                        $('#carregando').show();
                        window.location = '<?php echo $this->url(array("controller" => "agentes", "action" => "agentes")); ?>/id/' + data[0].idAgente;
                    }
                    else if (data[0].msgCPF == 'invalido') {
                        $('#erroCpf').html('CPF/CNPJ Inv&aacute;lido');
                    }
                    else if (data[0].msgCPF == 'novo') {
                        $('#novo').html('Preencha os dados abaixo!');
                        $('.novo').show();
                    }

                },
                error: function (data) {
                    alert("Falha na recupera&ccedil;&atilde;o dos dados.\nN&atilde;o foi poss&iacute;vel carregar agente!");
                }
            });

        }
    }

    function buscarcep(cep) {
        // pega os dados a serem populados
        var logradouro = document.getElementById("logradouro");
        var tipoLogradouro = document.getElementById("tipoLogradouro");
        var bairro = document.getElementById("bairro");
        var cidade = document.getElementById("cidade");
        var uf = document.getElementById("uf");
        var url = "<?php echo $this->url(array('module' => 'default', 'controller' => 'cep', 'action' => 'cep')); ?>?cep=" + cep;

        $('#erroCep').html("");
        if (cep.length != 10) {
            $('#erroCep').html("O CEP informado &eacute; inv&aacute;lido!");
            $("#logradouro, #bairro").val(' ');
            $("#cidade option[value=0]").html(" - Selecione - ");
            $("#uf option[value=0]").html(" - Selecione - ");
            $("#tipoLogradouro option[value=0]").html(" - Selecione - ");
            return false;
        }
        if (cep.length == 10) {

            $.ajax({
                url: url,
                dataType: "json",
                beforeSend: function () {

                    $(document).ajaxStart(function () {
                        $('#container-progress').fadeIn('slow');
                    });
                    $(document).ajaxComplete(function () {
                        $('#container-progress').fadeOut('slow');
                    });

                    $("#logradouro").attr("disabled", 'disabled');
                    $("#bairro").attr("disabled", 'disabled');

                    $("#logradouro").val("carregando...");
                    $("#bairro").val("carregando...");
                    $("#cidade option[value=0]").html("Carregando...");
                    $("#uf option[value=0]").html("Carregando...");

                    $3('select').material_select('destroy');
                    $3('select').material_select();

                    $('#erroCep').html("<img src='/public/img/ajax.gif' alt='' /> Aguarde...");
                },
                success: function (data) {
                    $('#erroCep').html("");
                    $('#logradouro').val(data.logradouro);
                    $('#complemento').val(data.complemento);
                    $('#bairro').val(data.bairro);
//                        $('#cidade > select > option[value="' + data.cidade + '"]').attr("selected", "selected");
                    $("#cidade option[value=0]").html(data.cidade).val(data.cod_cidade);
                    $("#uf option[value=0]").html(data.uf);

                    $3('select').material_select('destroy');
                    $3('select').material_select();

                    if (data.cidade == "") {
                        carregar_combo($("#uf").val(), 'cidade', '/cidade/combo', ' - Selecione - ');
                    }
                }
            });
        }
    }

    $(document).ready(function () {
        $3('select').material_select();
        var tipocpf = '<?php echo $this->tipocpf; ?>';
        var cpf = '<?php echo $this->cpf; ?>';


        if (tipocpf == 'cnpj') {
            filtroCNPJ();
        }
        if (tipocpf == 'cpf') {
            filtroCPF();
        }

        $("#cpf").val(cpf);
    });
</script>


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div id="novo">Novo cadastro<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <div id="confirma"></div>
    <div id="carregando" class="sumir">
        <table class="tabela">
            <tr>
                <td align="center" style="font-size: 18px;">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif"/><br/><br/>
                    Agente j&aacute; cadastrado, aguarde...
                </td>
            </tr>
        </table>
    </div>

    <div id="novocadastro">
        <form name="formCadAgentes" id="formCadAgentes" method="post"
              action="<?php echo $this->url(array('module' => 'agente', 'controller' => 'agentes', 'action' => 'salvaagentegeralexterno')); ?>">

            <input type="hidden" name="grupologado" id="grupologado" class="input_simples"
                   value="<?php echo $this->grupoativo; ?>"/>

            <center>
                <div id="cadDirigente" class="msgALERT sumir" style="width: 96%;">
                    <div style="float: left;">Você deve incluir pelo menos um dirigente ao finalizar seu cadastro!</div>
                </div>
            </center>

            <table id="tabDados" class="tabela">
                <tr>
                    <th colspan="3">DADOS PRINCIPAIS</th>
                </tr>
                <tr>
                    <td>
                        <input type="radio" name="Tipo" id="0" value="0" class="checkradio tipos"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"
                               checked="checked" onclick="filtroCPF();" onkeypress="filtroCPF();"/> <label
                            for="0">CPF</label> &nbsp;&nbsp;&nbsp;
                        <input type="radio" name="Tipo" id="1" value="1" class="checkradio tipos"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"
                               onclick="filtroCNPJ();" onkeypress="filtroCNPJ();"/> <label for="1">CNPJ</label>
                        <br/>
                        <label for="cpf"> </label>

                        <input class="input_simples" type="text" name="cpf" id="cpf" maxlength="14"
                               onkeyup="mascara(this, format_cpf);"
                               onclick="limpar_campo(this, ' ');"
                               onkeypress="limpar_campo(this, ' ');"
                               onblur="buscaragente(this.value);"
                               onmouseout="restaurar_campo(this, ' ');"
                               value="<?php echo $this->cpf; ?>"/>

                        &nbsp; <span id="erroCpf" class="spanError"></span>
                        <input type="hidden" id="idAgente" name="idAgente"/>
                    </td>
                    <td>
                        <label for="nome">Nome *</label>
                        <br/>
                        <input class="input_simples" type="text" name="nome" id="nome" maxlength="70" size="50"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');"/>

                        &nbsp; <span id="erroNome" class="spanError"></span>
                    </td>
                    <td align="center">
                        <label for="Visao"> Informe a vis&atilde;o do Agente: </label>

                        <select name="Visao" id="Visao"
                                onchange="verificarVisao(this.value, <?php echo $this->grupoAtivo; ?>);"
                                class="input_simples" style="width: 250px;">
                            <option value="0" selected="selected"> - Selecione -</option>
                            <?php foreach ($this->combovisoes as $combovisoes): ?>
                                <option
                                    value="<?php echo $combovisoes['idVerificacao']; ?>"> <?php echo $combovisoes['Descricao']; ?> </option>
                            <?php endforeach; ?>
                        </select>
                        &nbsp; <span id="erroVisao" class="spanError"></span>
                        &nbsp; <span id="spanVisao"></span>
                    </td>
                </tr>
            </table>

            <!-- ========== INÍCIO LISTA DE &aacute;REA ABERTA DE ACORDO COM A VIS&atilde;O ========== -->
            <div id="visaocomponente" class="sumir">

                <table id="tbvisaocomponente" class="tabela sumir">
                    <tr class="titulo_tabela">
                        <th colspan="4">LISTA DE &aacute;REA</th>
                    </tr>
                    <tr>
                        <td colspan="4" align="center">
                            <input type="radio" name="titular" id="titularS" value="1" class="checkradio"
                                   checked="checked"
                                   style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                            <label for="titularS">Titular</label>
                            <input type="radio" name="titular" id="titularN" value="0" class="checkradio"
                                   style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                            <label for="titularN">Suplente</label>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" valign="top">
                            <label for="areaCultural">&aacute;rea Cultural *</label>
                            <select name="areaCultural" id="areaCultural"
                                    onchange="carregar_combo(this.value, 'segmentoCultural', '<?php echo $this->url(array('controller' => 'segmentocultural', 'action' => 'combo')); ?>', ' - Selecione uma &aacute;rea Cultural - '), buscarareasegmento();"
                                    class="input_simples" style="width: 200px;">

                                <?php if (!isset($this->areaCultural) || empty($this->areaCultural)) { ?>
                                    <option value="0"> - Selecione -</option>
                                <?php } ?>

                                <?php foreach ($this->comboareasculturais as $comboareacultural): ?>
                                    <option
                                        value="<?php echo $comboareacultural->id; ?>" <?php if ($this->areaCultural == $comboareacultural->id) echo "selected=\"selected\""; ?>>
                                        <?php echo $comboareacultural->descricao; ?>
                                    </option>
                                <?php endforeach; ?>

                            </select>
                            &nbsp; <span id="erroAreaCultural" class="spanError"></span>

                            <span id="Q_titulares"></span>
                            <span id="Q_suplentes"></span>
                            <span id="msgAS" style="color:red; font-size:13px;font-weight: bold;"></span>
                            <span id="TitularSuplente"></span>

                        </td>
                        <td colspan="2" valign="top">
                            <label for="segmentoCultural">Segmento Cultural *</label>
                            <select name="segmentoCultural" id="segmentoCultural" onchange="buscarareasegmento();"
                                    class="input_simples" style="width: 200px;">

                                <?php if (!isset($this->areaCultural) || empty($this->areaCultural)) { ?>
                                    <option value="0"> - Selecione uma &aacute;rea Cultural -</option>
                                <?php } else { ?>

                                    <?php if (!isset($this->segmentoCultural) || empty($this->segmentoCultural)) { ?>
                                        <option value=""> - Selecione -</option>
                                    <?php } ?>

                                    <?php foreach ($this->combosegmentosculturais as $combosegmentocultural): ?>
                                        <option
                                            value="<?php echo $combosegmentocultural->id; ?>" <?php if ($this->segmentoCultural == $combosegmentocultural->id) echo "selected=\"selected\""; ?>>
                                            <?php echo $combosegmentocultural->descricao; ?>
                                        </option>
                                    <?php endforeach; ?>

                                <?php } ?>

                            </select>
                            &nbsp; <span id="erroSegmentoCultural" class="spanError"></span>
                        </td>
                    </tr>

                </table>
            </div>
            <!-- ========== FIM LISTA DE &aacute;REA ABERTA DE ACORDO COM A VIS&atilde;O ========== -->


            <!-- ========== INÍCIO FORMUL&aacute;RIO ENDERECO ========== -->
            <table id="tabEndereco" class="tabela">
                <tr>
                    <th colspan="3">Novo Endere&ccedil;o</th>
                </tr>
                <tr>
                    <td width="30%">
                        <label for="cep">CEP *</label><br/>
                        <input class="input_simples" type="text" name="cep" id="cep" maxlength="10"
                               onkeyup="mascara(this, format_cep);" onblur="buscarcep(this.value);"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');" value=" "/>

                        &nbsp; <span id="erroCep" class="spanError"></span>
                    </td>
                    <td width="30%">
                        <label for="uf">UF *</label> <br/>
                        <select name="uf" id="uf" class="input_simples"
                                onchange="carregar_combo(this.value,'cidade','<?php echo $this->url(array('controller' => 'cidade', 'action' => 'combo')); ?>',' - Selecione primeiro o UF - ');">

                            <?php if (!isset($this->uf) || empty($this->uf)) { ?>
                                <option value="0"> --</option>
                            <?php } ?>

                            <?php foreach ($this->comboestados as $comboestado): ?>
                                <option value="<?php echo $comboestado->id; ?>"
                                    <?php if ($this->uf == $comboestado->id) echo "selected=\"selected\""; ?> >
                                    <?php echo $comboestado->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroUf" class="spanError"></span>
                    </td>
                    <td>
                        <label for="cidade">Cidade *</label> <br/>
                        <select name="cidade" id="cidade" class="input_simples" style="width: 250px;">
                            <option value="0"> - Selecione -</option>

                            <?php foreach ($this->combocidades as $combocidade): ?>
                                <option value="<?php echo $combocidade->id; ?>"
                                        id="<?php echo $combocidade->idUF; ?>"
                                    <?php if ($this->cidade == $combocidade->id) echo "selected=\"selected\""; ?>>
                                    <?php echo $combocidade->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroCidade" class="spanError"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="tipoEndereco">Tipo de Endere&ccedil;o *</label> <br/>
                        <select name="tipoEndereco" id="tipoEndereco" class="input_simples" style="width: 250px;">

                            <?php if (!isset($this->tipoEndereco) || empty($this->tipoEndereco)) { ?>
                                <option value="0"> - Selecione -</option>
                            <?php } ?>

                            <?php foreach ($this->combotiposenderecos as $combotipoendereco): ?>
                                <option value="<?php echo $combotipoendereco->id; ?>"
                                    <?php if ($this->tipoEndereco == $combotipoendereco->id) echo "selected=\"selected\""; ?>>
                                    <?php echo $combotipoendereco->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroTipoEndereco" class="spanError"></span>
                    </td>
                    <td>
                        <label for="tipoLogradouro">Tipo de Logradouro *</label> <br/>
                        <select name="tipoLogradouro" id="tipoLogradouro" class="input_simples" style="width: 250px;">

                            <?php if (!isset($this->tipoLogradouro) || empty($this->tipoLogradouro)) { ?>
                                <option value="0"> - Selecione -</option>
                            <?php } ?>

                            <?php foreach ($this->combotiposlogradouros as $comboTipoLogradouro): ?>
                                <option value="<?php echo $comboTipoLogradouro->id; ?>"
                                    <?php if ($this->tipoLogradouro == $comboTipoLogradouro->id) echo "selected=\"selected\""; ?>>
                                    <?php echo $comboTipoLogradouro->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroTipoLogradouro" class="spanError"></span>
                    </td>
                    <td>
                        <label for="logradouro">Logradouro *</label> <br/>
                        <input class="input_simples" type="text" name="logradouro" id="logradouro" maxlength="50"
                               size="50"/>
                        <span id="erroLogradouro" class="spanError"></span>
                    </td>
                </tr>
                <tr>

                    <td>
                        <label for="numero">Número</label> <br/>
                        <input class="input_simples" type="text" name="numero" id="numero" maxlength="10" size="30"/>
                        <span id="erroNumero" class="spanError"></span>
                    </td>
                    <td>
                        <label for="complemento">Complemento</label> <br/>
                        <input class="input_simples" type="text" name="complemento" id="complemento" maxlength="70"
                               size="50"/>
                        <span id="erroComplemento" class="spanError"></span>
                    </td>
                    <td>
                        <label for="bairro">Bairro *</label> <br/>
                        <input class="input_simples" type="text" name="bairro" id="bairro" maxlength="70" size="50"/>
                        <span id="erroBairro" class="spanError"></span>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <label>Autorizo divulgar o endere&ccedil;o</label>
                        <input type="radio" name="divulgarEndereco" id="divulgarEnderecoS" value="1" class="checkradio"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneS">Sim</label>
                        <input type="radio" name="divulgarEndereco" id="divulgarEnderecoN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneN">N&atilde;o</label>
                    </td>
                </tr>
            </table>
            <!-- ========== FIM FORMUL&aacute;RIO ENDERECO ========== -->


            <!-- ========== INÍCIO FORMUL&aacute;RIO FONE ========== -->
            <table id="tabFone" class="tabela">
                <tr>
                    <th colspan="5">TELEFONE</th>
                </tr>
                <tr>
                    <td>
                        <label for="tipoFone">Tipo *</label>
                        <br/>
                        <select name="tipoFone" id="tipoFone" class="input_simples">
                            <option value=""> - Selecione -</option>

                            <?php foreach ($this->combotipostelefones as $combotipotelefone) { ?>
                                <option
                                    value="<?php echo $combotipotelefone->id; ?>"><?php echo $combotipotelefone->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroTipoFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="ufFone">UF *</label>
                        <br/>
                        <select name="ufFone" id="ufFone" class="input_simples"
                                onchange="carregar_combo(this.value,'dddFone','<?php echo $this->url(array('controller' => 'ddd', 'action' => 'combo')); ?>');">
                            <option value="0"> --</option>

                            <?php foreach ($this->comboestados as $combouffone) { ?>
                                <option
                                    value="<?php echo $combouffone->id; ?>"><?php echo $combouffone->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroUfFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="dddFone">DDD *</label>
                        <br/>
                        <select name="dddFone" id="dddFone" class="input_simples">
                            <option value=""> --</option>
                        </select>

                        &nbsp; <span id="erroDddFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="fone">Telefone *</label>
                        <br/>
                        <input type="text" name="fone" id="fone" maxlength="9" class="input_simples w100"
                               onkeyup="mascara(this, format_tel);"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');" value=" "/>

                        &nbsp; <span id="erroFone" class="spanError"></span>
                    </td>
                    <td>
                        <label>Divulgar? *</label>
                        <br/>
                        <input type="radio" name="divulgarFone" id="divulgarFoneS" value="1" class="checkradio"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneS">Sim</label>
                        <input type="radio" name="divulgarFone" id="divulgarFoneN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneN">N&atilde;o</label>
                    </td>
                </tr>

                <tr>
                    <th colspan="5">E-MAIL</th>
                </tr>
                <tr>
                    <td>
                        <label for="tipoEmail">Tipo *</label>
                        <br/>
                        <select name="tipoEmail" id="tipoEmail" class="input_simples">
                            <option value="0">- Selecione -</option>

                            <?php foreach ($this->combotiposemails as $combotipoemail) { ?>
                                <option
                                    value="<?php echo $combotipoemail->id; ?>"><?php echo $combotipoemail->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroTipoEmail" class="spanError"></span>
                    </td>
                    <td>
                        <label for="email">E-mail *</label>
                        <br/>
                        <input type="text" name="email" id="email" class="input_simples w200" size="50" maxlength="70"
                               onclick="limpar_campo(this, ' ');"
                               onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');"
                               onmouseout="restaurar_campo(this, ' ');"
                               value=" "/>

                        &nbsp; <span id="erroEmail" class="spanError"></span>
                    </td>
                    <td colspan="3">
                        <label>Posso Divulgar? *</label>
                        <br/>
                        <input type="radio" name="divulgarEmail" id="divulgarEmailS" value="1"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarEmailS">Sim</label>
                        <input type="radio" name="divulgarEmail" id="divulgarEmailN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarEmailN">N&atilde;o</label>
                    </td>
                </tr>

            </table>
            <!-- ========== FIM FORMUL&aacute;RIO E-MAIL ========== -->

            <table class="tabela">
                <tr>
                    <td class="centro"><input type="button" class="btn_salvar" value=" " onclick="validaAgenteNovo();"/>
                    </td>
                </tr>
            </table>

        </form>

    </div>


</div>
<!-- ========== FIM CONTEÚDO ========== -->


<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all"/>
