<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>var $3 = jQuery.noConflict();</script>
<script src="<?php echo $this->baseUrl(); ?>/public/library/materialize/js/materialize.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/animate.css">

<style type="text/css">
    label{
        font-weight: normal;
        margin-right: 15px;
    }

    div .termo {
        margin: 0 auto;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <h3>Desistência do Prazo Recursal</h3>
        <form name="form" id="form" action="<?php echo $this->url(array('controller' => 'solicitarrecursodecisao', 'action' => 'recurso-desistencia-enquadramento')); ?>?idPronac=<?php echo $this->projetos->IdPRONAC; ?>" method="post">
            <input type="hidden" name="idPronac" id="idPronac" value="<?php echo $this->projetos->IdPRONAC; ?>" />
            <table>
                <tr>
                    <th>Pronac</th>
                    <th>Nome do Projeto</th>
                </tr>
                <tr>
                    <td align="center"><?php echo $this->projetos->AnoProjeto.$this->projetos->Sequencial; ?></td>
                    <td align="center"><?php echo $this->projetos->NomeProjeto; ?></td>
                </tr>
            </table>
            <div class="card-panel grey lighten-3 z-depth-4 termo">
                <p>Prezado Proponente, a manifesta&ccedil;&atilde;o de concordância com os termos da decis&atilde;o da Comiss&atilde;o Nacional de Incentivo &agrave; Cultura - CNIC relativa ao seu projeto cultural apreciado na última Reuni&atilde;o implica em renúncia &agrave; possibilidade de encaminhamento de pedido de reconsidera&ccedil;&atilde;o conforme disposto no art. 44 da Instru&ccedil;&atilde;o Normativa nº 1, de 24/6/2013:</p>
                <p style="font-style: italic;">"Art. 44.  Da decis&atilde;o caber&aacute; pedido de reconsidera&ccedil;&atilde;o, no prazo de dez dias corridos, a contar do seu registro no Salic."</p>
                <p>Dessa forma, ao concluir o procedimento de concordância que &eacute; facultativo, o seu projeto cultural ser&aacute; automaticamente encaminhado, juntamente com os demais projetos na mesma situa&ccedil;&atilde;o, para an&aacute;lise da decis&atilde;o da CNIC e verifica&ccedil;&atilde;o da instru&ccedil;&atilde;o processual com vistas &agrave; publica&ccedil;&atilde;o da Portaria que autoriza a capta&ccedil;&atilde;o de recursos incentivados no Di&aacute;rio Oficial da Uni&atilde;o - DOU, independentemente do prazo referido no art. 44.</p>
                <br clear="all">
            </div>
            <div class="input-field col s12 center-align">
                <a
                    data-ajax-modal-height="400px"
                    data-ajax-modal="<?php echo $this->url(array('module' => 'default', 'controller'=> 'solicitarrecursodecisao', 'action' => 'concordar-desistencia-recursal-modal'));?>?idPronac=<?php echo $this->projetos->IdPRONAC;?>" class="tooltipped waves-effect waves-light btn modal-trigger" data-tooltip="Concordar com os Termos" href="#modal1">Concordo
                    <i class="material-icons right modal-trigger">send</i>
                </a>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'));?>?idPronac=<?php echo $this->projetos->IdPRONAC; ?>"
                   class="tooltipped red-text btn waves-effect waves-dark white"
                   data-tooltip="Cancelar Desistência"
                   id="btn_cancelar"
                   name="action">
                    Cancelar
                </a>
            </div>
        </form>
    </div>
</div>
<!--<div id="modal1" class="modal">-->
<!--    <div class="modal-content">-->
<!--      <p>Tem certeza? Essa decis&atilde;o n&atilde;o pode ser revertida.</p>-->
<!--    </div>-->
<!--    <div class="modal-footer">-->
<!--      <a href="--><?php //echo $this->url(array('module' => 'default', 'controller' => 'consultardadosprojeto', 'action' => 'index'));?><!--?idPronac=--><?php //echo $this->projetos->IdPRONAC;?><!--" class=" modal-action modal-close waves-effect waves-red btn-flat">Discordo</a>-->
<!--        <a href="--><?php //echo $this->url(array('module' => 'default', 'controller'=> 'solicitarrecursodecisao', 'action' => 'recurso-desistencia-enquadramento-salvar'));?><!--?idPronac=--><?php //echo $this->projetos->IdPRONAC;?><!--" class=" modal-action modal-close waves-effect waves-green btn-flat">Concordo</a>-->
<!--    </div>-->
<!--</div>-->
<!--<script type="text/javascript">-->
<!--        $3(document).ready(function () {-->
<!--            $3('.modal').modal();-->
<!--        });-->
<!--</script>-->
