<?php
echo $this->partial('inc/menu.inc.php', $this) ?>
<script type="text/javascript">


    function buscaragente(cpf) {
        $('#erroCpf').html('Aguarde!');

        value = $("#cpf").val();

        if (value == '') {
            $('#erroCpf').html('Informe o CPF/CNPJ!');
        }
        else if (value.length < 14) {
            $('#erroCpf').html('CPF Incompleto!');
        }
        else if (value.length != 14) {
            $('#erroCpf').html('CPF inv&aacute;lido!');
        }
        else {
            $('#erroCpf').html('');
            // retira as m&aacute;scaras do cpf/cnpj
            value = value.replace(".", "");
            value = value.replace(".", "");
            value = value.replace("/", "");
            cpf = value.replace("-", "");

            // faz a verifica&ccedil;&atilde;o do agente via post
            $.ajax({
                type: "POST",
                dataType: 'json',
                data: {
                    cpf: cpf
                },
                url: '<?php echo $this->url(array("controller" => "alterarprojeto", "action" => "agentecadastrado")); ?>',

                success: function (data) {
                    if (data[0].msgCPF == 'cadastrado') {
                        $('#novocadastro').hide();
                        $('#carregando').show();
                        <?php if ( $this->idDirigente == "true" ) { ?>
                        window.location = '<?php echo $this->url(array("controller" => "alterarprojeto", "action" => "visualizadirigente", "id" => $this->id)); ?>';
                        <?php } else{?>
                        window.location = '<?php echo $this->url(array("controller" => "alterarprojeto", "action" => "visualizadirigente", "id" => $this->id)); ?>/idDirigente/' + data[0].idAgente;
                        <?php } ?>
                    }
                    else if (data[0].msgCPF == 'invalido') {
                        $('#erroCpf').html('CPF/CNPJ Inv&aacute;lido');
                    }
                    else if (data[0].msgCPF == 'novo') {
                        $('#novo').html('Preencha os dados abaixo!');
                        $('.novo').show();
                    }

                },
                error: function (data) {
                    alert("Falha na recupera&ccedil;&atilde;o dos dados.\nN&atilde;o foi poss&iacute;vel carregar agente!");
                }
            });

        }
    }


    function buscarcep(cep) {
        // pega os dados a serem populados
        var logradouro = document.getElementById("logradouro");
        var tipoLogradouro = document.getElementById("tipoLogradouro");
        var bairro = document.getElementById("bairro");
        var cidade = document.getElementById("cidade");
        var uf = document.getElementById("uf");
        var url = "<?php echo $this->url(array('module' => 'default', 'controller' => 'cep', 'action' => 'cep')); ?>?cep=" + cep;

        $('#erroCep').html("");
        if (cep.length != 10) {
            $('#erroCep').html("O CEP informado &eacute; inv&aacute;lido!");
            $("#logradouro, #bairro").val(' ');
            $("#cidade option[value=0]").html(" - Selecione - ");
            $("#uf option[value=0]").html(" - Selecione - ");
            $("#tipoLogradouro option[value=0]").html(" - Selecione - ");
            return false;
        }
        if (cep.length == 10) {

            $.ajax({
                url: url,
                dataType: "json",
                beforeSend: function () {

                    $(document).ajaxStart(function () {
                        $('#container-progress').fadeIn('slow');
                    });
                    $(document).ajaxComplete(function () {
                        $('#container-progress').fadeOut('slow');
                    });

                    $("#logradouro").attr("disabled", 'disabled');
                    $("#bairro").attr("disabled", 'disabled');

                    $("#logradouro").val("carregando...");
                    $("#bairro").val("carregando...");
                    $("#cidade option[value=0]").html("Carregando...");
                    $("#uf option[value=0]").html("Carregando...");

                    $3('select').material_select('destroy');
                    $3('select').material_select();

                    $('#erroCep').html("<img src='/public/img/ajax.gif' alt='' /> Aguarde...");
                },
                success: function (data) {
                    $('#erroCep').html("");
                    $('#logradouro').val(data.logradouro);
                    $('#complemento').val(data.complemento);
                    $('#bairro').val(data.bairro);
//                        $('#cidade > select > option[value="' + data.cidade + '"]').attr("selected", "selected");
                    $("#cidade option[value=0]").html(data.cidade).val(data.cod_cidade);
                    $("#uf option[value=0]").html(data.uf);

                    $3('select').material_select('destroy');
                    $3('select').material_select();

                    if (data.cidade == "") {
                        carregar_combo($("#uf").val(), 'cidade', '/cidade/combo', ' - Selecione - ');
                    }
                }
            });
        }
    }

    $(document).ready(function () {
            $3('select').material_select();
        }
    );

</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="#" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li><a href="#" title="Tramita&ccedil;&atilde;o de Documentos">Manter Agentes</a></li>
        <li class="last">Principal</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->


<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div id="novo">Incluir Dirigente<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->


<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <div id="carregando" class="sumir">
        <table class="tabela">
            <tr>
                <td align="center" style="font-size: 18px;">
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif"/><br/><br/>
                    Agente j&aacute; cadastrado, aguarde...
                </td>
            </tr>
        </table>
    </div>

    <div id="novocadastro">
        <form name="formCadAgentes" id="formCadAgentes" method="post"
              action="<?php echo $this->url(array('controller' => 'alterarprojeto', 'action' => 'salvadirigentegeral')); ?>?pronac=<?php echo $_GET['pronac'] ?>">

            <input type="hidden" name="grupologado" id="grupologado" class="input_simples"
                   value="<?php echo $this->grupoativo; ?>"/>

            <table id="tabDados" class="tabela">
                <tr>
                    <th colspan="6">DADOS PRINCIPAIS</th>
                </tr>
                <tr>
                    <td>
                        <label for="cpf">CPF *</label>
                        <br/>
                        <input class="input_simples" type="text" name="cpf" id="cpf" maxlength="14"
                               onkeyup="mascara(this, format_cpf);"
                               onclick="limpar_campo(this, ' ');"
                               onkeypress="limpar_campo(this, ' ');"
                               onblur="buscaragente(this.value);"
                               onmouseout="restaurar_campo(this, ' ');"
                               value=""/>

                        &nbsp; <span id="erroCpf" class="spanError"></span>
                        <input type="hidden" id="idAgente" name="idAgente"/>
                    </td>
                    <td>
                        <label for="nome">Nome *</label>
                        <br/>
                        <input class="input_simples" type="text" name="nome" id="nome" maxlength="70" size="50"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');"/>

                        &nbsp; <span id="erroNome" class="spanError"></span>
                    </td>
                    <td align="center">
                        <label for="Visao"> Informe a vis&atilde;o do Agente: </label>

                        <select name="Visao" id="Visao"
                                onchange="verificarVisao(this.value, <?php echo $this->grupoAtivo; ?>);"
                                class="input_simples" style="width: 250px;">
                            <option value="198" selected="selected">Dirigente de institui&ccedil;&atilde;o</option>
                        </select>
                        &nbsp; <span id="erroVisao" class="spanError"></span>
                        &nbsp; <span id="spanVisao"></span>
                    </td>
                </tr>
            </table>


            <!-- ========== INÍCIO FORMUL&aacute;RIO ENDERECO ========== -->
            <table id="tabEndereco" class="tabela">
                <tr>
                    <th colspan="3">Novo Endere&ccedil;o</th>
                </tr>
                <tr>
                    <td width="30%">
                        <label for="cep">CEP *</label><br/>
                        <input class="input_simples" type="text" name="cep" id="cep" maxlength="10"
                               onkeyup="mascara(this, format_cep);" onblur="buscarcep(this.value);"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');" value=" "/>

                        &nbsp; <span id="erroCep" class="spanError"></span>
                    </td>
                    <td width="30%">
                        <label for="uf">UF *</label> <br/>
                        <select name="uf" id="uf" disabled="disabled" class="input_simples"
                                onchange="carregar_combo(this.value,'cidade','<?php echo $this->url(array('controller' => 'cidade', 'action' => 'combo')); ?>',' - Selecione primeiro o UF - ');">

                            <?php if (!isset($this->uf) || empty($this->uf)) { ?>
                                <option value="0"> --</option>
                            <?php } ?>

                            <?php if ($this->comboestados) : ?>
                                <?php foreach ($this->comboestados as $comboestado): ?>
                                    <option value="<?php echo $comboestado->id; ?>"
                                        <?php if ($this->uf == $comboestado->id) echo "selected=\"selected\""; ?> >
                                        <?php echo $comboestado->descricao; ?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif; ?>

                        </select>
                        <span id="erroUf" class="spanError"></span>
                    </td>
                    <td>
                        <label for="cidade">Cidade *</label> <br/>
                        <select name="cidade" disabled="disabled" id="cidade" class="input_simples"
                                style="width: 250px;">
                            <option value="0"> - Selecione -</option>

                            <?php if ($this->combocidades) : ?>
                                <?php foreach ($this->combocidades as $combocidade): ?>
                                    <option value="<?php echo $combocidade->id; ?>"
                                            id="<?php echo $combocidade->idUF; ?>"
                                        <?php if ($this->cidade == $combocidade->id) echo "selected=\"selected\""; ?>>
                                        <?php echo $combocidade->descricao; ?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif; ?>

                        </select>
                        <span id="erroCidade" class="spanError"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="tipoEndereco">Tipo de Endere&ccedil;o *</label> <br/>
                        <select name="tipoEndereco" id="tipoEndereco" class="input_simples" style="width: 250px;">

                            <?php if (!isset($this->tipoEndereco) || empty($this->tipoEndereco)) { ?>
                                <option value="0"> - Selecione -</option>
                            <?php } ?>

                            <?php foreach ($this->combotiposenderecos as $combotipoendereco): ?>
                                <option value="<?php echo $combotipoendereco->id; ?>"
                                    <?php if ($this->tipoEndereco == $combotipoendereco->id) echo "selected=\"selected\""; ?>>
                                    <?php echo $combotipoendereco->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroTipoEndereco" class="spanError"></span>
                    </td>
                    <td>
                        <label for="tipoLogradouro">Tipo de Logradouro *</label> <br/>
                        <select name="tipoLogradouro" id="tipoLogradouro" class="input_simples" style="width: 250px;">

                            <?php if (!isset($this->tipoLogradouro) || empty($this->tipoLogradouro)) { ?>
                                <option value="0"> - Selecione -</option>
                            <?php } ?>

                            <?php foreach ($this->combotiposlogradouros as $comboTipoLogradouro): ?>
                                <option value="<?php echo $comboTipoLogradouro->id; ?>"
                                    <?php if ($this->tipoLogradouro == $comboTipoLogradouro->id) echo "selected=\"selected\""; ?>>
                                    <?php echo $comboTipoLogradouro->descricao; ?>
                                </option>
                            <?php endforeach; ?>

                        </select>
                        <span id="erroTipoLogradouro" class="spanError"></span>
                    </td>
                    <td>
                        <label for="logradouro">Logradouro *</label> <br/>
                        <input class="input_simples" disabled="disabled" type="text" name="logradouro" id="logradouro"
                               maxlength="50" size="50"/>
                        <span id="erroLogradouro" class="spanError"></span>
                    </td>
                </tr>
                <tr>

                    <td>
                        <label for="numero">Número *</label> <br/>
                        <input class="input_simples" type="text" name="numero" id="numero" maxlength="10" size="30"/>
                        <span id="erroNumero" class="spanError"></span>
                    </td>
                    <td>
                        <label for="complemento">Complemento</label> <br/>
                        <input class="input_simples" type="text" name="complemento" id="complemento" maxlength="70"
                               size="50"/>
                        <span id="erroComplemento" class="spanError"></span>
                    </td>
                    <td colspan="2">
                        <label for="bairro">Bairro *</label> <br/>
                        <input class="input_simples" disabled="disabled" type="text" name="bairro" id="bairro"
                               maxlength="70" size="50"/>
                        <span id="erroBairro" class="spanError"></span>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <label>Autorizo divulgar o endere&ccedil;o</label>
                        <input type="radio" name="divulgarEndereco" id="divulgarEnderecoS" value="1" class="checkradio"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneS">Sim</label>
                        <input type="radio" name="divulgarEndereco" id="divulgarEnderecoN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneN">N&atilde;o</label>
                    </td>
                </tr>
            </table>
            <!-- ========== FIM FORMUL&aacute;RIO ENDERECO ========== -->


            <!-- ========== INÍCIO FORMUL&aacute;RIO FONE ========== -->
            <table id="tabFone" class="tabela">
                <tr>
                    <th colspan="5">TELEFONE</th>
                </tr>
                <tr>
                    <td>
                        <label for="tipoFone">Tipo *</label>
                        <br/>
                        <select name="tipoFone" id="tipoFone" class="input_simples">
                            <option value=""> - Selecione -</option>

                            <?php foreach ($this->combotipostelefones as $combotipotelefone) { ?>
                                <option
                                    value="<?php echo $combotipotelefone->id; ?>"><?php echo $combotipotelefone->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroTipoFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="ufFone">UF *</label>
                        <br/>
                        <select name="ufFone" id="ufFone" class="input_simples"
                                onchange="carregar_combo(this.value,'dddFone','<?php echo $this->url(array('controller' => 'ddd', 'action' => 'combo')); ?>');">
                            <option value="0"> --</option>

                            <?php foreach ($this->comboestados as $combouffone) { ?>
                                <option
                                    value="<?php echo $combouffone->id; ?>"><?php echo $combouffone->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroUfFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="dddFone">DDD *</label>
                        <br/>
                        <select name="dddFone" id="dddFone" class="input_simples">
                            <option value=""> --</option>
                        </select>

                        &nbsp; <span id="erroDddFone" class="spanError"></span>
                    </td>
                    <td>
                        <label for="fone">Telefone *</label>
                        <br/>
                        <input type="text" name="fone" id="fone" maxlength="9" class="input_simples w100"
                               onkeyup="mascara(this, format_tel);"
                               onclick="limpar_campo(this, ' ');" onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');" onmouseout="restaurar_campo(this, ' ');" value=" "/>

                        &nbsp; <span id="erroFone" class="spanError"></span>
                    </td>
                    <td>
                        <label>Divulgar? *</label>
                        <br/>
                        <input type="radio" name="divulgarFone" id="divulgarFoneS" value="1" class="checkradio"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneS">Sim</label>
                        <input type="radio" name="divulgarFone" id="divulgarFoneN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarFoneN">N&atilde;o</label>
                    </td>
                </tr>

                <tr>
                    <th colspan="5">E-MAIL</th>
                </tr>
                <tr>
                    <td>
                        <label for="tipoEmail">Tipo *</label>
                        <br/>
                        <select name="tipoEmail" id="tipoEmail" class="input_simples">
                            <option value="0">- Selecione -</option>

                            <?php foreach ($this->combotiposemails as $combotipoemail) { ?>
                                <option
                                    value="<?php echo $combotipoemail->id; ?>"><?php echo $combotipoemail->descricao; ?></option>
                            <?php } ?>

                        </select>

                        &nbsp; <span id="erroTipoEmail" class="spanError"></span>
                    </td>
                    <td>
                        <label for="email">E-mail *</label>
                        <br/>
                        <input type="text" name="email" id="email" class="input_simples w200" size="50" maxlength="70"
                               onclick="limpar_campo(this, ' ');"
                               onkeypress="limpar_campo(this, ' ');"
                               onblur="restaurar_campo(this, ' ');"
                               onmouseout="restaurar_campo(this, ' ');"
                               value=" "/>

                        &nbsp; <span id="erroEmail" class="spanError"></span>
                    </td>
                    <td colspan="3">
                        <label>Posso Divulgar? *</label>
                        <br/>
                        <input type="radio" name="divulgarEmail" id="divulgarEmailS" value="1"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarEmailS">Sim</label>
                        <input type="radio" name="divulgarEmail" id="divulgarEmailN" value="0" class="checkradio"
                               checked="checked"
                               style="background: none; border: 0%; float:none; clear:auto; display:inline;"/>
                        <label for="divulgarEmailN">N&atilde;o</label>
                    </td>
                </tr>

            </table>
            <!-- ========== FIM FORMUL&aacute;RIO E-MAIL ========== -->

            <table class="tabela">
                <tr>
                    <td class="centro"><input type="button" class="btn_salvar" value=" "
                                              onclick="validaDirigenteNovo();"/></td>
                </tr>
            </table>

        </form>

    </div>


</div>
<!-- ========== FIM CONTEÚDO ========== -->


<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all"/>
