<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINIST&eacute;RIO DA CULTURA<br>
    Secretaria de Fomento e Incentivo &agrave; Cultura<br>
    Esplanada dos Minist&eacute;rios, Bloco "B"<br>
    Brasília/DF - CEP 70.068-900
</p>
<div>
    <p lang="pt-BR" align="LEFT">
    <strong>
        Comunicado nº ____/<?php echo date('Y'); ?>
    </strong>
    </p>
    <p lang="pt-BR" align="LEFT">
        <strong> </strong>
    </p>
    <p lang="pt-BR" align="RIGHT">
        Brasília-DF, ___/ ___/ _____.
    </p>
    <p lang="pt-BR" align="LEFT">
        &agrave; </br>
        Brincante Produ&ccedil;&otilde;es Artísticas Ltda. </br>
        Comercial - Rua - Purpurina - 428 - Sumarezinho - teatro </br>
        S&atilde;o Paulo /SP </br>
        CEP: 05.435-030
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        Projeto: {nomeProjeto}</br>
        Proponente: {nomeProponente}</br>
        Processo: {processo}</br>
        Pronac: {pronac}
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        1. No exercício das competências legalmente atribuídas ao Minist&eacute;rio da Cultura, comunicamos a Vossa Senhoria que a an&aacute;lise da presta&ccedil;&atilde;o de contas do
        projeto em referência foi concluída e <strong>APROVADA</strong> por este Minist&eacute;rio e que est&atilde;o disponíveis para consulta no Sistema de Apoio &agrave;s Leis de
        Incentivo &agrave; Cultura (SalicWeb) o Relatório de Execu&ccedil;&atilde;o, a Avalia&ccedil;&atilde;o da Presta&ccedil;&atilde;o de Contas e o Laudo acerca da presta&ccedil;&atilde;o de contas do projeto acima.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
    2. Ressaltamos que documentos fiscais, relatórios e demais documentos pertinentes ao projeto em referência dever&atilde;o ser guardados pelo prazo mínimo de    <strong>10 (dez) anos</strong>, conforme art. 83 da Instru&ccedil;&atilde;o Normativa MinC nº 01/2013, <em>in verbis</em>:
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        "
        <em>
            Art. 83. Cabe ao proponente emitir comprovantes em favor dos doadores ou patrocinadores, bem como manter o controle documental das receitas e despesas
            do projeto pelo prazo de dez anos, contados da aprova&ccedil;&atilde;o da presta&ccedil;&atilde;o de contas, &agrave; disposi&ccedil;&atilde;o do MinC e dos órg&atilde;os de controle e fiscaliza&ccedil;&atilde;o, caso
            seja instado a apresent&aacute;-las, conforme previsto no art. 36 da Instru&ccedil;&atilde;o Normativa RFB nº 1.131, de 21 de fevereiro de 2011
        </em>
        ".
    </p>
    <p lang="pt-BR">
        3. Por oportuno, colocamo-nos &agrave; disposi&ccedil;&atilde;o para quaisquer dúvidas a respeito do assunto em pauta, bem como registramos nossa satisfa&ccedil;&atilde;o pela conclus&atilde;o
        dessa exitosa a&ccedil;&atilde;o desenvolvida em prol da cultura brasileira.
    </p>
    <p lang="pt-BR" align="LEFT">
        Atenciosamente,
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorIncentivoACultura}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura
    </p>
</div>