<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINIST&eacute;RIO DA CULTURA <br>
    Secretaria de Fomento e Incentivo &agrave; Cultura <br>
    Diretoria de Incentivo &agrave; Cultura <br>
    Coordena&ccedil;&atilde;o-Geral de Presta&ccedil;&atilde;o de Contas <br>
    Esplanada dos Minist&eacute;rios, Bloco "B" - Bras&iacute;lia/DF - CEP: 70.068-900
</p>
<div>
    <p>
        <strong>Laudo Final sobre a Presta&ccedil;&atilde;o de Contas nº ____/<?php echo date('Y'); ?>.</strong>
    </p>
    <p>
        Projeto: {nomeProjeto} <br>
        Proponente: {nomeProponente} <br>
        Processo: {processo} <br>
        Pronac: {pronac}
    </p>
    <p>
        1. Conforme as determina&ccedil;&otilde;es previstas no Par&aacute;grafo único do artigo 70 e no inciso II da Constitui&ccedil;&atilde;o Federal, conjugados com as determina&ccedil;&otilde;es da Lei n°
        8.313/1991 e outras regulamenta&ccedil;&otilde;es espec&iacute;ficas, esta Coordena&ccedil;&atilde;o Geral realizou a an&aacute;lise sobre a execu&ccedil;&atilde;o financeira do projeto identificado.
    </p>
    <p>
        2. Destarte, após comprovado o cumprimento do objeto e a correta aplica&ccedil;&atilde;o dos recursos públicos, conforme demonstram o Relatório de Execu&ccedil;&atilde;o emitido pela
        Coordena&ccedil;&atilde;o-Geral de Acompanhamento e Avalia&ccedil;&atilde;o/CGAAV/DIC/SEFIC/MinC e a Avalia&ccedil;&atilde;o da Presta&ccedil;&atilde;o de Contas emitida por esta Coordena&ccedil;&atilde;o-Geral de Presta&ccedil;&atilde;o
        de Contas/CGEPC/DIC/SEFIC/MinC, a gest&atilde;o empreendida no presente projeto cultural foi qualificada como<strong> REGULAR</strong> quanto &agrave; aderência entre as
        realiza&ccedil;&otilde;es e a programa&ccedil;&atilde;o aprovada, proporcionalidade entre os produtos e os aportes realizados e cumprimento das prescri&ccedil;&otilde;es legais e normativas
        regentes da mat&eacute;ria.
    </p>
    <p>
        3. Ressalta-se que a decis&atilde;o quanto &agrave; regularidade das contas pode ser revista a qualquer tempo, de forma justificada, o que consiste no poder-dever de a
        própria Administra&ccedil;&atilde;o exercer o controle de seus atos, atuando por provoca&ccedil;&atilde;o do particular ou de of&iacute;cio, reapreciando os atos produzidos em seu âmbito,
        an&aacute;lise esta que pode incidir sobre a legalidade do ato ou quanto ao seu m&eacute;rito.
    </p>
    <p>
        Respeitosamente,
    </p>
    <p align="right">
        ___/ ___/ ____.
    </p>
    <p align="center">
        <strong>{coordenadorIncentivoFiscal}</strong>
    </p>
    <p align="center">
        Coordenador(a) de Incentivos Fiscais e Apoio T&eacute;cnico
    </p>
    <p>
        De acordo com o presente Laudo, proponho o encaminhamento dos autos para o(a) Sr(a). Diretor(a) de Incentivo &agrave; Cultura com sugest&atilde;o de aprova&ccedil;&atilde;o da Presta&ccedil;&atilde;o de
        Contas.
    </p>
    <p align="right">
        ___/ ___/ ____.
    </p>
    <p align="center">
        <strong>{coordenadorPrestacaoDeContas}</strong>
    </p>
    <p align="center">
        Coordenador(a) Geral de Presta&ccedil;&atilde;o de Contas
    </p>
    <p>
        De acordo com o presente Laudo, proponho o encaminhamento dos autos para o(a) Sr(a). Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura com sugest&atilde;o de aprova&ccedil;&atilde;o da
        Presta&ccedil;&atilde;o de Contas.
    </p>
    <p align="right">
        ___/ ___/ ____.
    </p>
    <p>
        <strong></strong>
    </p>
    <p align="center">
        <strong></strong>
    </p>
    <p align="center">
        <strong></strong>
    </p>
    <p align="center">
        <strong>{diretorIncentivoACultura}</strong>
    </p>
    <p align="center">
        Diretor(a) de Incentivo &agrave; Cultura
    </p>
    <p>
        De acordo com o presente Laudo, aprovo a Presta&ccedil;&atilde;o de Contas. Comunique-se, publique-se e arquive-se.
    </p>
    <p align="right">
        ___/ ___/ ____.
    </p>
    <p align="center">
        <strong></strong>
    </p>
    <p align="center">
        <strong></strong>
    </p>
    <p align="center">
        <strong></strong>
    </p>
    <p align="center">
        <strong>{coordenadorIncentivoACultura}</strong>
    </p>
    <p align="center">
        Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura
    </p>
</div>