<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout - Mensagens
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('manual-layout/inc/menu.inc.phtml', $this)// menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utiliza&ccedil;&atilde;o do Layout">Exemplo de Utiliza&ccedil;&atilde;o do Layout</a></li>
		<li class="last">Mensagens</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Mensagens
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<div id="miolo">
		<h4 class="centro">Mensagens em PHP (dentro das controllers)</h4>

		<p class="bold">parent::message("Mensagem de advertência!", "controller/action", "ALERT");</p>
		<div class="msgALERT">
			<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgALERT" onclick="$('.msgALERT').hide();" onkeypress="$('.msgALERT').hide();"/></div>
			<div>Mensagem de advertência!</div>
		</div>

		<br />

		<p class="bold">parent::message("Mensagem de sucesso!", "controller/action", "CONFIRM");</p>
		<div class="msgCONFIRM">
			<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgCONFIRM" onclick="$('.msgCONFIRM').hide();" onkeypress="$('.msgCONFIRM').hide();"/></div>
			<div>Mensagem de sucesso!</div>
		</div>

		<br />

		<p class="bold">parent::message("Mensagem de erro!", "controller/action", "ERROR");</p>
		<div class="msgERROR">
			<div class="float_right"><input type="button" class="btn_close" title="Fechar mensagem" id="msgERROR" onclick="$('.msgERROR').hide();" onkeypress="$('.msgERROR').hide();"/></div>
			<div>Mensagem de erro!</div>
		</div>


		<br />
		<br />


		<h4 class="centro">Mensagens em JS (dentro das views)</h4>

		<strong>&lt;p class="msg"&gt;Mensagem de erro, valida&ccedil;&atilde;o de formul&aacute;rios, etc.&lt;/p&gt;</strong>
		<br />
		<p class="msg">Mensagem de erro, valida&ccedil;&atilde;o de formul&aacute;rios, etc.</p>

		<br />
		<br />

		<strong>&lt;label class="error"&gt;Mensagem de erro, valida&ccedil;&atilde;o de formul&aacute;rios, etc.&lt;/label&gt;</strong>
		<br />
		<label class="error">Mensagem de erro, valida&ccedil;&atilde;o de formul&aacute;rios, etc.</label>
	</div>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />