<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout - P&aacute;gina com Menu Lateral
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('manual-layout/inc/menu.inc.phtml', $this)// menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utiliza&ccedil;&atilde;o do Layout">Exemplo de Utiliza&ccedil;&atilde;o do Layout</a></li>
		<li class="last">P&aacute;gina com menu lateral</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		P&aacute;gina com menu lateral
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<div id="miolo">
		<p>Esse &eacute; o esqueleto de uma p&aacute;gina com menu lateral.</p>

		<br />

		<p>
			Crie uma pasta chamada <strong>inc</strong> dentro de sua view e utilize o arquivo 
			<strong>/NovoSalic/application/views/scripts/manual-layout/manual-layout/inc/menu.inc.phtml</strong> como exemplo.
		</p>

		<br />

		<p>
			Inclua o arquivo no in&iacute;cio da view que utilizar&aacute; o menu lateral: 
			<strong>require_once "manual-layout/inc/menu.inc.phtml";</strong>
		</p>
	</div>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />