<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout - Tabelas
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('manual-layout/inc/menu.inc.phtml', $this)// menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utiliza&ccedil;&atilde;o do Layout">Exemplo de Utiliza&ccedil;&atilde;o do Layout</a></li>
		<li class="last">Tabelas</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Tabelas
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- ========== INÍCIO TABELA ========== -->
	<table class="tabela">
		<thead>
			<tr>
				<th>Título (thead)</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Linha simples (sem classe).</td>
			</tr>
			<tr class="linha">
				<td>Utilize a classe .linha (passe o mouse em cima)</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Utilize a classe .fundo_linha2</td>
			</tr>
			<tr class="fundo_linha3">
				<td>Utilize a classe .fundo_linha3</td>
			</tr>
			<tr class="fundo_linha4">
				<td>Utilize a classe .fundo_linha4</td>
			</tr>
			<tr class="fundo_linha5">
				<td>Utilize a classe .fundo_linha5</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td>Rodap&eacute; (tfoot)</td>
			</tr>
		</tfoot>
	</table>
	<!-- ========== FIM TABELA ========== -->

	<br />

	<div class="miolo">
		<h4 class="centro">Tabela padr&atilde;o com os dados do projeto:</h4>
	</div>

	<table class="tabela">
		<tr>
			<th width="50%">Pronac</th>
			<th>Nome do Projeto</th>
		</tr>
		<tr class="linha">
			<td>101234</td>
			<td>Projeto Saber</td>
		</tr>
		<tr>
			<th width="50%">CNPJ/CPF</th>
			<th>Nome do Proponente</th>
		</tr>
		<tr class="linha">
			<td>123.456.789-09</td>
			<td>Fulano de Tal</td>
		</tr>
	</table>

	<br />

	<div class="miolo">
		<h4 class="centro">Considera&ccedil;&otilde;es para tabelas de registros vindos do banco:</h4>
	</div>

	<!-- ========== INÍCIO TABELA ========== -->
	<table class="tabela">
		<thead>
			<tr>
				<th>Título (thead)</th>
			</tr>
		</thead>
		<tbody class="registros">
			<tr>
				<td>Toda tabela deve utilizar a classe <strong>.tabela</strong></td>
			</tr>
			<tr class="fundo_linha2">
				<td>Prefira os título dentro de <strong>thead</strong>, conteúdo geral dentro de <strong>tbody</strong> e rodap&eacute; dentro de <strong>tfoot</strong></td>
			</tr>
			<tr>
				<td>Todo título deve estar dentro da tag <strong>th</strong></td>
			</tr>
			<tr class="fundo_linha2">
				<td>Alterne as cores das linhas: a primeira linha sem classe e a segunda utilizando a classe <strong>.fundo_linha2</strong></td>
			</tr>
			<tr>
				<td>Adicione efeitos ao passar o mouse em cima das linhas de registros: utilize a classe <strong>.registros</strong> dentro de <strong>tbody</strong> ou de <strong>tr</strong></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td>Rodap&eacute; (tfoot)</td>
			</tr>
		</tfoot>
	</table>
	<!-- ========== FIM TABELA ========== -->

	<br />

	<div class="miolo">
		<h4 class="centro">Tabelas com largura alterada:</h4>
	</div>

	<!-- ========== INÍCIO TABELA ========== -->
	<div class="miolo">

		<!-- ========== INÍCIO TABELA ALINHADA &agrave; ESQUERDA ========== -->
		<div class="w400 float_left">
			<table class="tabela">
				<thead>
					<tr>
						<th>Tabela alinhada &agrave; esquerda</th>
					</tr>
				</thead>
				<tbody>
					<tr class="linha">
						<td>Para alterar a largura padr&atilde;o de uma tabela utilize a classe <strong>.w500</strong>, onde 500 &eacute; a largura em pixels.</td>
					</tr>
					<tr class="linha">
						<td>Para alinhar a tabela &agrave; esqueda utilize a classe <strong>.float_left</strong>.</td>
					</tr>
					<tr>
						<td class="bg_red white">
							Se for alinhar a tabela &agrave; esquerda, prefira utilizar a classe <strong>.float_left</strong> em uma <strong>div</strong>. 
							Dentro dessa <strong>div</strong> insira a tabela normalmente. 
							Dessa forma o alinhamento ser&aacute; obedecido nos navegadores Internet Explorer, Firefox e Chrome.
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<!-- ========== FIM TABELA ALINHADA &agrave; ESQUERDA ========== -->

		<!-- ========== INÍCIO TABELA ALINHADA &agrave; DIREITA ========== -->
		<div class="w400 float_right">
			<table class="tabela">
				<thead>
					<tr>
						<th>Tabela alinhada &agrave; direita</th>
					</tr>
				</thead>
				<tbody>
					<tr class="linha">
						<td>Para alterar a largura padr&atilde;o de uma tabela utilize a classe <strong>.w500</strong>, onde 500 &eacute; a largura em pixels.</td>
					</tr>
					<tr class="linha">
						<td>Para alinhar a tabela &agrave; direita utilize a classe <strong>.float_right</strong>.</td>
					</tr>
					<tr>
						<td class="bg_red white">
							Se for alinhar a tabela &agrave; direita, prefira utilizar a classe <strong>.float_right</strong> em uma <strong>div</strong>. 
							Dentro dessa <strong>div</strong> insira a tabela normalmente. 
							Dessa forma o alinhamento ser&aacute; obedecido nos navegadores Internet Explorer, Firefox e Chrome.
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<!-- ========== FIM TABELA ALINHADA &agrave; DIREITA ========== -->

		<!-- ========== INÍCIO TABELA CENTRALIZADA ========== -->
		<table class="tabela w400">
			<thead>
				<tr>
					<th>Tabela centralizada</th>
				</tr>
			</thead>
			<tbody>
				<tr class="linha">
					<td>Para alterar a largura padr&atilde;o de uma tabela utilize a classe <strong>.w500</strong>, onde 500 &eacute; a largura em pixels.</td>
				</tr>
				<tr>
					<td class="bg_blue white">Para colocar essa tabela centralizada, basta colocar seu código fonte abaixo da alinhada &agrave; esqueda e da alinhada &agrave; direita.</td>
				</tr>
			</tbody>
		</table>
		<!-- ========== FIM TABELA CENTRALIZADA ========== -->

	</div>
	<!-- ========== FIM TABELA ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />