<div id="menu">
<!-- in&iacute;cio: conteúdo principal #container -->
    <div id="container">
        <?php echo $this->partial('gerarrelatorioparecerista/inc/menu.inc.php', $this);?>
        <!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
        <div id="breadcrumb">
                <ul>
                        <li class="first"><a href="index.phtml" title="Ir para In&iacute;cio">In&iacute;cio</a></li>

                        <li class="last">Principal</li>
                </ul>
        </div>
        <!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
        <!-- ========== BUTTON VOLTAR ========== -->
        <div id="titulo">
                <div>Projetos com parecer t&eacute;cnico consolidado<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
        </div>
        <!-- ========== FIM TÍTULO ========== -->
        <!-- ========== GRID NOME DA PROPOSTA ========== -->
        <div id="conteudo" align="center">
            <div style="height: 100px;">
            </div>
        </div>
        <!-- ========== FIM CONTEÚDO ========== -->
        <!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
        <div id="rodapeConteudo"><span></span></div>
        <!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->
        <br clear="all" />
    </div>
</div>
