engines:

  phpcodesniffer:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        - "php"

  phan:
    enabled: true
    config:
      file_extensions: "php"

  phpmd:
    enabled: true

exclude_paths:
    - "codeclimate-master/"
    - "doc/"
    - "docker/"
    - "library/"
    - "public/"
    - "sql/"
    - "tests/"

