<?php
/**
 * Login do Sistema
 * @author Equipe RUP - Politec
 * @since 12/03/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.login
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>
<!-- ========== INÍCIO TÍTULO ========== -->

<div id="titulo">
    <div>Aviso!</div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo" style="font-size: 20px; color: red;">
    <div style="margin: 20px;">
        <p>O sistema estar&aacute; indispon&iacute;vel a partir das 14 horas desta ter&ccedil;a-feira, 05/03/2013, voltando &agrave; normalidade &agrave;s 18 horas da ter&ccedil;a-feira, 05/03/2013.</p>
        <p>O objetivo da a&ccedil;&atilde;o &eacute; promover teste de stress no servidor de aplica&ccedil;&atilde;o para avaliarmos a quantidade de conex&otilde;es que o equipamento suporta.</p>
        <p>A medida implica na suspens&atilde;o tempor&aacute;ria de acesso.</p>
    </div>
</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<br clear="all" />
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->