<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout
 * @author Tarc&iacute;sio Angelo - XTI
 * @since 11/01/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.comunicados
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('inc/menu.inc.phtml', $this)// menu lateral
?>

<script type="text/javascript">
	jqAjaxLink('<?php echo $this->Url(array('controller' => 'comunicados', 'action' => 'listar-comunicados', 'stEstado' => '0')) ?>', '', 'resultadoConsulta');
</script>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'comunicados', 'action' => 'index'), '', true); ?>" title="Ir para P&aacute;gina Comunicados">Comunicados</a></li>
		<li class="last">Comunicados desativados</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Comunicados desativados
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<div id="resultadoConsulta"><br><center>Aguarde, carregando dados...<br><img src="<?php echo $this->baseUrl(); ?>/public/img/ajax.gif" /></center><br></div>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />