<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout
 * @author Tarcísio Angelo - XTI
 * @since 11/01/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.comunicados
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('inc/menu.inc.phtml', $this)// menu lateral
?>

<script type="text/javascript">
<!--
	/**
	 * Fun&ccedil;&otilde;es que s&atilde;o chamadas após a p&aacute;gina ser carregada
	 */
	$(document).ready(function()
	{
		// m&aacute;scaras dos campos
		$("#periodo1, #periodo2").keyup(function()
		{
			mascara(this, format_data); // data
		});

		// calend&aacute;rio
		$.datepicker.regional['pt-BR'] = 
		{
			closeText: 'Fechar',
			prevText: '&#x3c;Anterior',
			nextText: 'Pr&oacute;ximo&#x3e;',
			currentText: 'Hoje',
			monthNames: ['Janeiro','Fevereiro','Mar&ccedil;o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
			monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
			dayNames: ['Domingo','Segunda-feira','Ter&ccedil;a-feira','Quarta-feira','Quinta-feira','Sexta-feira','S&aacute;bado'],
			dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
			dayNamesMin: ['Dom','Seg','Ter','Qua','Qui','Sex','Sab'],
			weekHeader: 'Sm',
			dateFormat: 'dd/mm/yy',
			firstDay: 0,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ''
		};
		$.datepicker.setDefaults($.datepicker.regional['pt-BR']);

		// id dos campos que utilizar&atilde;o o calend&aacute;rio
		$("#dtInicioVigencia, #dtTerminoVigencia").datepicker($.datepicker.regional['pt-BR']);
		
		CKEDITOR.replace('comunicado');
		
	}); // fim $(document).ready()
	
	
	function validaForm()
	{
		var comunicado = CKEDITOR.instances['comunicado'].getData().toString().replace(/(<.*?>)|(&nbsp;)|(\s+)/g,'');
		
		var dtinicio = $("#dtInicioVigencia").val();
		var dtfim = $("#dtTerminoVigencia").val();
		var dtAtual = $("#dtatual").val();

        if(dtinicio != '' && compararDataInicialDataFinal(dtinicio, dtAtual) == 0)
	    {
			alertar('A data inicial n&atilde;o pode ser menor que a data atual!');
            return false;
        }
        
        if(dtfim != '' && compararDataInicialDataFinal(dtinicio, dtfim) != 0)
	    {
			alertar('A data final deve ser maior que a data inicial!');
            return false;
        }
        
        if (comunicado.length == 0)
        {
            alertar('O campo comunicado &eacute; obrigatório!');
            return false;
        }
        
        $("#formnovo").submit();
        

	}
	
	
	//-->
</script>


<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'comunicados', 'action' => 'index'), '', true); ?>" title="Ir para P&aacute;gina Comunicados">Comunicados</a></li>
		<li class="last">Novo</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<div id="confirma"></div>

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Novo comunicado
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

<input type="hidden" name="dtatual" id="dtatual" value="<?php echo date("d/m/Y");?>" />

	<!-- ========== INÍCIO FORMUL&aacute;RIO 1 ========== -->
	<form name="formnovo" id="formnovo" action="<?php echo $this->url(array('controller' => 'comunicados', 'action' => 'salvar')); ?>" method="POST">
	<input type="hidden" name="stEstado" value="1" />
	
		<table class="tabela">
			<tr>
				<td>
					<label for="stOpcao0">Op&ccedil;&atilde;o: </label>&nbsp;&nbsp;&nbsp;
					<label for="stOpcao0">SALIC</label>&nbsp;
					<input type="radio" name="stOpcao" id="stOpcao0" value="0" class="input_simples" checked="checked" />
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					<label for="stOpcao1">PROPOSTA</label>&nbsp;
					<input type="radio" name="stOpcao" id="stOpcao1" value="1" class="input_simples" />
				</td>
			</tr>
		</table>
		<table class="tabela">	
			<tr>
				<td align="center" colspan="2">
					<label for="comunicado">Comunicado</label><br />
					<textarea name="comunicado" id="comunicado" class="textarea_simples w400 h200"></textarea>
				</td>
			</tr>
			<tr>
				<td align="">
					<label for="dtInicioVigencia">In&iacute;cio de vigência </label>&nbsp;
					<input type="text" name="dtInicioVigencia" id="dtInicioVigencia" maxlength="10" class="input_simples btn_calendario" />
				</td>
				<td align="">
					<label for="dtTerminoVigencia">Fim de vigência</label>&nbsp;
					<input type="text" name="dtTerminoVigencia" id="dtTerminoVigencia" maxlength="10" class="input_simples btn_calendario" />
				</td>
			</tr>
		</table>

		<table class="tabela">
			<tr>
				<td colspan="4" class="centro">
					<input type="button" value=" " title="Salvar" class="btn_salvar" onclick="return validaForm();" />
				</td>
			</tr>
		</table>
	</form>
	<!-- ========== FIM FORMUL&aacute;RIO 1 ========== -->


</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />