<?php


//echo $this->partial('inc/menu.inc.php', $this) // menu
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''),'',true); ?>" title="Ir para Início">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'gerenciarpareceres', 'action' => 'index'),'',true); ?>" title="Gerenciar Pareceres">Gerenciar Pareceres T&eacute;cnicos</a></li>
		<li class="last">Consolida&ccedil;&atilde;o manual de Pareceres</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Consolida&ccedil;&atilde;o manual de Pareceres<span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<table class="tabela">
		<tr>
			<td align="center" style="font-size:15px; color:#000">
				<br />
				A consolida&ccedil;&atilde;o de Pareceres &eacute; uma tarefa automatizada pelo Sistema,<br />
				no entanto, você pode for&ccedil;ar uma consolida&ccedil;&atilde;o neste momento.
				<br />
				<br />
			</td>
		</tr>
	</table>
	
	<table class="tabela">
		<tr>
			<td align="center">
				<input type="button" class="btn_confirmar" style="width:88px;" name="btn_confirmar" value=" " onclick="redirecionar('./execconsolidacao');"/>
				<input type="button" class="btn_voltar" name="btn_voltar" value=" " onclick="voltar();"/>
			</td>
		</tr>
	</table>




</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />