<img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" class="corrigir-periodo-captacao" style="cursor: pointer" />

<div id="mensagem" class="sumir">
    <p>Efetue a corre&ccedil;&atilde;o dessa inconsistência, prorrogando o período de capta&ccedil;&atilde;o do projeto.
        <br>
        Após efetuar a devida corre&ccedil;&atilde;o, clicar novamente no bot&atilde;o 'Validar Itens'.
    </p>
    <ul style="margin-left: 15px;">
        <li>Diligenciar ao proponente informando-o a pedir a prorroga&ccedil;&atilde;o do prazo de capta&ccedil;&atilde;o de recursos do projeto;</li>
        <li>O proponente responde a diligência e tamb&eacute;m faz o pedido da prorroga&ccedil;&atilde;o da capta&ccedil;&atilde;o de recursos do projeto;</li>
        <li>O t&eacute;cnico defere ou n&atilde;o este pedido.</li>
    </ul>
</div>

<script>
    $('.corrigir-periodo-captacao').click(function () {
        $("#msgAlerta").dialog("destroy");
        $("#msgAlerta").html($('#mensagem').html());
        $("#msgAlerta").dialog({
            resizable: false,
            title: 'Alerta!',
            width: 730,
//            height: 500,
            modal: true
        });
    });
</script>