<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('/manual-layout/inc/menu.inc.phtml', $this)// menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">In&iacute;cio</a></li>
		<li class="last">Exemplo de utiliza&ccedil;&atilde;o do layout</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		Exemplo de utiliza&ccedil;&atilde;o do layout
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- t&iacute;tulos -->
	<fieldset>
		<legend>T&iacute;tulos</legend>
		<h1>T&iacute;tulo utilizando <strong>h1</strong>.</h1>
		<h2>T&iacute;tulo utilizando <strong>h2</strong>.</h2>
		<h3>T&iacute;tulo utilizando <strong>h3</strong>.</h3>
		<h4>T&iacute;tulo utilizando <strong>h4</strong>.</h4>
		<h5>T&iacute;tulo utilizando <strong>h5</strong>.</h5>
		<h6>T&iacute;tulo utilizando <strong>h6</strong>.</h6>
	</fieldset>



	<!-- par&aacute;grafos, links, imagens, etc -->
	<fieldset>
		<legend>Par&aacute;grafos, Estilos, Links e Imagens</legend>

		<!-- ========== INÍCIO MARGEM ========== -->
		<div id="miolo">
			<p class="bold">Par&aacute;grafo 1:</p>
			<p>
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>.
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 2 (identado):</p>
			<p class="identar">
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>.
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 3 (acrônimo e links):</p>
			<p>
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o.
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 4 (imagem simples):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" />
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 5 (imagem com borda):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="imagem" />
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 6 (imagem com texto):</p>
			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="float_left" />
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong> com imagem alinhada &agrave; esquerda. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>.
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o.
			</p>

			<br />

			<p>
				<img src="<?php echo $this->baseUrl(); ?>/public/img/logo.png" alt="Logomarca do sistema SALIC" class="float_right" />
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong> com imagem alinhada &agrave; direita. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>.
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o. 
				Exemplo de par&aacute;grafo utilizando a tag <strong>p</strong>. 
				Quando uma p&aacute;gina possui somente textos &eacute; necess&aacute;rio coloc&aacute;-los dentro de uma <strong>div</strong> 
				com o atributo <strong>id="miolo"</strong> para que se tenha uma margem do conteúdo em rela&ccedil;&atilde;o ao layout. 
				Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
				Para identar um par&aacute;grafo basta utilizar a classe <strong>.identar</strong>. 
				O sistema <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> est&aacute; dispon&iacute;vel no 
				endere&ccedil;o eletrônico <a href="http://salic.cultura.gov.br" title="Acessar http://salic.cultura.gov.br">http://salic.cultura.gov.br</a>. 
				Passe o mouse em cima do texto <acronym title="Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura">SALIC</acronym> para ver sua descri&ccedil;&atilde;o.
			</p>

			<br />
			<br />

			<p class="bold">Par&aacute;grafo 7 (cores e estilos de texto e links):</p>
			<p class="red">Utilize a classe <strong>.red</strong></p>
			<p class="green">Utilize a classe <strong>.green</strong></p>
			<p class="blue">Utilize a classe <strong>.blue</strong></p>
			<p class="orange">Utilize a classe <strong>.orange</strong></p>
			<p class="black">Utilize a classe <strong>.black</strong> ou <strong>.white</strong> para utilizar as cores preto ou branco</p>
			<p class="bg_red white">Utilize a classe <strong>.bg_red</strong></p>
			<p class="bg_green white">Utilize a classe <strong>.bg_green</strong></p>
			<p class="bg_blue white">Utilize a classe <strong>.bg_blue</strong></p>
			<p class="bg_orange white">Utilize a classe <strong>.bg_orange</strong></p>
			<p class="bg_white black">Utilize a classe <strong>.bg_white</strong></p>
			<p class="bg_black white">Utilize a classe <strong>.bg_black</strong></p>
			<p>
				<a href="#" title="Link com cor alterada" class="bg_red">
					<span class="white">
						Para link com cor diferente utilize a tag <strong>span</strong> dentro do mesmo e adicione a classe desejada
					</span>
				</a>
			</p>
			<p class="del_link">
				<a href="#" title="Link sem underline">
					<span class="green">
						Para link sem underline utilize a classe <strong>.del_link</strong> dentro de um elemento "pai" do link
					</span>
				</a>
			</p>
		</div>
		<!-- ========== FIM MARGEM ========== -->

	</fieldset>



	<!-- agrupamento de formul&aacute;rios -->
	<fieldset>
		<legend>Grupo 1</legend>
		Junte grupos de formul&aacute;rios utilizando a tag <strong>fieldset</strong>, e, coloque sua descri&ccedil;&atilde;o utilizando a tag <strong>legend</strong>.
	</fieldset>
	<fieldset>
		<legend>Grupo 2</legend>
		Junte grupos de formul&aacute;rios utilizando a tag <strong>fieldset</strong>, e, coloque sua descri&ccedil;&atilde;o utilizando a tag <strong>legend</strong>.
	</fieldset>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />