<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout - M&aacute;scaras em JS
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */

echo $this->partial('manual-layout/inc/menu.inc.phtml', $this)// menu lateral
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utiliza&ccedil;&atilde;o do Layout">Exemplo de Utiliza&ccedil;&atilde;o do Layout</a></li>
		<li class="last">M&aacute;scaras em js</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		M&aacute;scaras em js
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<table class="tabela">
		<thead>
			<tr>
				<th colspan="3">M&aacute;scaras em Campos de Formul&aacute;rios Utilizando JavaScript</th>
			</tr>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			<tr>
				<th>Descri&ccedil;&atilde;o</th>
				<th>Fun&ccedil;&atilde;o</th>
				<th>Exemplo</th>
			</tr>
		</thead>
		<tbody class="registros">
			<tr>
				<td>Aceitar somente números inteiros.</td>
				<td class="centro"><strong>format_num()</strong></td>
				<td>
					&lt;input type="text" name="idade" id="idade" maxlength="3" <strong>onkeyup="mascara(this, format_num);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="idade" id="idade" maxlength="3" onkeyup="mascara(this, format_num);" class="input_simples" />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Aceitar somente números no formato float.</td>
				<td class="centro"><strong>format_float()</strong></td>
				<td>
					&lt;input type="text" name="decimal" id="decimal" maxlength="10" <strong>onkeyup="mascara(this, format_float);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="decimal" id="decimal" maxlength="10" onkeyup="mascara(this, format_float);" class="input_simples" />
				</td>
			</tr>
			<tr>
				<td>Aceitar somente formato de moeda.</td>
				<td class="centro"><strong>format_moeda()</strong></td>
				<td>
					&lt;input type="text" name="valor" id="valor" maxlength="12" <strong>onkeyup="mascara(this, format_moeda);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="valor" id="valor" maxlength="12" onkeyup="mascara(this, format_moeda);" class="input_simples" />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Aceitar somente números no formato de milhar.</td>
				<td class="centro"><strong>format_num_pontos()</strong></td>
				<td>
					&lt;input type="text" name="qtd" id="qtd" maxlength="10" <strong>onkeyup="mascara(this, format_num_pontos);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="qtd" id="qtd" maxlength="10" onkeyup="mascara(this, format_num_pontos);" class="input_simples" />
				</td>
			</tr>
			<tr>
				<td>Aceitar somente formato de datas.</td>
				<td class="centro"><strong>format_data()</strong></td>
				<td>
					&lt;input type="text" name="data" id="data" maxlength="10" <strong>onkeyup="mascara(this, format_data);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="data" id="data" maxlength="10" onkeyup="mascara(this, format_data);" class="input_simples" />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Aceitar somente formato de telefone com ddd.</td>
				<td class="centro"><strong>format_fone()</strong></td>
				<td>
					&lt;input type="text" name="fone" id="fone" maxlength="14" <strong>onkeyup="mascara(this, format_fone);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="fone" id="fone" maxlength="14" onkeyup="mascara(this, format_fone);" class="input_simples" />
				</td>
			</tr>
			<tr>
				<td>Aceitar somente formato de telefone sem ddd.</td>
				<td class="centro"><strong>format_tel()</strong></td>
				<td>
					&lt;input type="text" name="fone" id="fone" maxlength="9" <strong>onkeyup="mascara(this, format_tel);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="fone" id="fone" maxlength="9" onkeyup="mascara(this, format_tel);" class="input_simples" />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Aceitar somente formato de cpf.</td>
				<td class="centro"><strong>format_cpf()</strong></td>
				<td>
					&lt;input type="text" name="cpf" id="cpf" maxlength="14" <strong>onkeyup="mascara(this, format_cpf);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="cpf" id="cpf" maxlength="14" onkeyup="mascara(this, format_cpf);" class="input_simples" />
				</td>
			</tr>
			<tr>
				<td>Aceitar somente formato de cnpj.</td>
				<td class="centro"><strong>format_cnpj()</strong></td>
				<td>
					&lt;input type="text" name="cnpj" id="cnpj" maxlength="18" <strong>onkeyup="mascara(this, format_cnpj);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="cnpj" id="cnpj" maxlength="18" onkeyup="mascara(this, format_cnpj);" class="input_simples" />
				</td>
			</tr>
			<tr class="fundo_linha2">
				<td>Aceitar somente formato de cpf ou cnpj.</td>
				<td class="centro"><strong>mascaraCnpjCpf()</strong></td>
				<td>
					&lt;input type="text" name="cpf_cnpj" id="cpf_cnpj" maxlength="18" <strong>onkeyup="mascaraCnpjCpf(this);"</strong> class="input_simples" /&gt;<br />
					<input type="text" name="cpf_cnpj" id="cpf_cnpj" maxlength="18" onkeyup="mascaraCnpjCpf(this);" class="input_simples" />
				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
		</tfoot>
	</table>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />