<?php
/**
 * Exemplo de Utiliza&ccedil;&atilde;o do Layout - P&aacute;gina Simples
 * @author emanuel.sampaio - Politec
 * @since 27/05/2011
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.manual-layout
 * @link http://salic.cultura.gov.br
 * @copyright © 2011 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => '', 'action' => ''), '', true); ?>" title="Ir para P&aacute;gina Inicial">Início</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'manual-layout', 'action' => ''), '', true); ?>" title="Ir para Exemplo de Utiliza&ccedil;&atilde;o do Layout">Exemplo de Utiliza&ccedil;&atilde;o do Layout</a></li>
		<li class="last">P&aacute;gina simples</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>
		P&aacute;gina simples
		<span class="voltar"><a href="javascript:voltar();" title="P&aacute;gina Anterior">Voltar</a></span>
	</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	Esse &eacute; o esqueleto de uma p&aacute;gina simples, sem menu. 
	Caso a p&aacute;gina contenha textos fora de tabelas, crie uma <strong>div</strong> 
	com o atributo <strong>id="miolo"</strong> e coloque o conteúdo dentro da mesma. 
	Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
	Esse &eacute; um exemplo de texto que est&aacute; fora de <strong>&lt;div id="miolo"&gt; &lt;/div&gt;</strong>.

	<br />

	<div id="miolo">
		Esse &eacute; o esqueleto de uma p&aacute;gina simples, sem menu. 
		Caso a p&aacute;gina contenha textos fora de tabelas, crie uma <strong>div</strong> 
		com o atributo <strong>id="miolo"</strong> e coloque o conteúdo dentro da mesma. 
		Caso precise utilizar a margem mais de uma vez na mesma p&aacute;gina, utilize o atributo <strong>class="miolo"</strong>. 
		Esse &eacute; um exemplo de texto que est&aacute; dentro de <strong>&lt;div id="miolo"&gt; &lt;/div&gt;</strong>.
	</div>

	<br />

	<table class="tabela">
		<tr>
			<th>Esqueleto de P&aacute;gina Simples</th>
		</tr>
		<tr>
			<td>Esse &eacute; o esqueleto de uma p&aacute;gina simples, sem menu.</td>
		</tr>
	</table>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />