<?php
/**
 * Rodap&eacute; do Sistema
 * @author Equipe RUP - Politec
 * @since 29/03/2010
 * @version 1.0
 * @package application
 * @subpackage application.layout
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

echo "\n\t<!-- ========== INÍCIO RODAP&eacute; ========== -->";
echo "\n\t<div id='rodape'>";
echo "\n\t\t<div><strong>MINIST&Eacute;RIO DA CULTURA</strong></div>";
echo "\n\t</div>";
echo "\n\t<div id=\"alerta\"></div>";
echo "\n\t<!-- ========== FIM RODAP&eacute; ========== -->";
echo "\n\t</body>";
echo "\n</html>";
?>
