<?php
/**
 * Carrega o Layout Padr&atilde;o do Sistema (scriptcase)
 * @author Equipe RUP - Politec
 * @since 29/03/2010
 * @version 1.0
 * @package application
 * @subpackage application.layout
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

/* ========== TOPO ========== */
echo $this->render('header_scriptcase.phtml');



/* ========== CONTEÚDO ========== */
echo $this->layout()->content;



/* ========== RODAP&eacute; ========== */
echo $this->render('footer_scriptcase.phtml');
?>