<script>
    function vinculaResposavel(idAgente)
    {
            $("#acao").dialog({
            title :'Vincular',
            resizable: false,
            width:400,
            height:200,
            modal: true,
            autoOpen:false,
            buttons: {
                'N&atilde;o': function() {
                    $(this).dialog('close');
                },
                'Sim': function() {
                    location.href="<?php echo $this->url(array('controller' => 'vincularresponsavel', 'action' => 'desvincularresponsavel')); ?>?idAgente="+idAgente;
                }
            }
        });
        $("#acao").dialog('open');
    }

</script>
<div id="acao" style="display:none">Deseja realmente desvincular este respons&aacute;vel?</div>
<!-- ========== INICIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => '')); ?>" title="Ir para Início">Início</a></li>
        <li class="last">Respons&aacute;vel Vinculado</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INICIO TITULO ========== -->
<div id="titulo">
    <div>Desvincular Respons&aacute;vel<span>ID #23A</span> <span class="voltar"><a href="#" onclick="redirecionar('<?php echo $this->url(array('controller' => 'vincularresponsavel', 'action' => 'index')); ?>');">Voltar</a></span></div>
</div>
<!-- ========== FIM TITULO ========== -->



<!-- ========== INICIO CONTEUDO ========== -->
<div id="conteudo">

    <fieldset>

        <table class="tabela" summary="Esta tabela cont&eacute;m os dados dos Agentes pertencentes &aacute; Institui&ccedil;&atilde;oe e que podem ser desvinculados">
            <tr>
                <td colspan="3" class="titulo_tabela">Respons&aacute;vel Vinculado</td>
            </tr>
            <tr>
                <th>CPF</th>
                <th >Nome</th>
                <th >Desvincular</th>
            </tr>
       <?php foreach ($this->buscaragentes as $agentes) {       ?>


            <tr>
                <td ><?php echo $agentes->CNPJCPF ?></td>
                <td ><?php echo $agentes->Descricao ?></td>
                <td style="cursor:hand" onclick="vinculaResposavel('<?php echo $agentes->idAgente ?>')"><img alt="vincular" src="<?php echo $this->baseUrl()?>/public/img/passed.gif"></td>
            </tr>


        <?php }?>


        </table>


    </fieldset>




</div>
<!-- ========== FIM CONTEUDO ========== -->



<!-- ========== INICIO RODAPE DO CONTEUDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAPE DO CONTEUDO ========== -->
<br clear="all" />
