<div class="sumir" id="email">
    Deseja solicitar o v&iacute;nculo ao proponente?
</div>
<fieldset>
    <legend>Vincular ao Proponente</legend>
    <table class="tabela">
        <tr>
             <th colspan="3" class="w500">Vincular ao Proponente</th>
        </tr>
        <tr class="destacar">
            <td tabindex="1"><b>CPF:</b></td>
            <td tabindex="1"><b>Nome:</b></td>
            <td tabindex="1"><b>Solicitar V&iacute;nculo:</b></td>
        </tr>
        <?php $idAgente = null; ?>

        <?php foreach ($this->vinculo as $vinculo): ?>

            <?php if($vinculo->idAgente != $idAgente):?>
	            <tr class="centro">
	                <td align="left"> <?php echo Validacao::mascaraCPFCNPJ($vinculo->CNPJCPF); ?></td>
	                <td align="left"><?php echo $vinculo->nomeagente ?></td>
	                <td style="font-weight: 600;">
		                <?php if(($vinculo->usuariovinculo) == null): ?>
		                	<?php if(($vinculo->siVinculo != '')): ?>
		                		<?php echo $this->stVinculo($vinculo->siVinculo); ?>
		                	<?php else:   ?>
		                        <img style="cursor: pointer;" class="vincular" id="vincular" onclick="vincularproponente('<?php echo $vinculo->idAgente; ?>');" idAgente="<?php echo $vinculo->idAgente; ?>" src="<?php echo $this->baseUrl(); ?>/public/img/passed.gif" />
		                	<?php endif;?>
		                <?php else: ?>
		                	Servidor do Minist&eacute;rio da Cultura n&atilde;o pode ser Proponente!
		                <?php endif; ?>
	                </td>
	            </tr>
	        <?php $idAgente = $vinculo->idAgente; ?>
	        <?php endif;?>
        <?php endforeach; ?>
    </table>
</fieldset>

