<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="In&iacute;cio">In&iacute;cio</a></li>
        <li class="last">Solicitar Altera&ccedil;&atilde;o Projeto</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Solicitar Altera&ccedil;&atilde;o Projeto <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

<table class="tabela"  >

            <tr>
            	<td class="titulo_tabela">Projeto Cultural</td>
            </tr>
            <tr align="center">
            	<th>Ficha T&eacute;cnica</th>
            </tr>
            
</table>
<table class="tabela"  >
            <tr>
                <td class="titulo_dentro">Identifica&ccedil;&atilde;o</td>                
            </tr>
            <?php foreach ($this->resposta as $resposta) {?>
            <tr>
                <td><strong>Pronac:</strong> <br>         <?php echo $this->escape($resposta->idPronac); ?></td>
                <td><strong>Nome do Projeto:</strong> <br><?php echo $this->escape($resposta->NomeProjeto); ?></td>
            </tr>
         
          
                     
           <tr>
                <td><strong>CNPJ / CPF:</strong> <br>
                <?php 
                	$arr2 = str_split($this->escape($resposta->CgcCpf), 3); 
                	echo $arr2["0"].".".$arr2["1"].".".$arr2["2"]."-".$arr2["3"]; 
                ?>
                </td>
                <td><strong>Proponente:</strong> <br><?php echo $this->escape($resposta->Nome); ?></td>
           </tr>
           <?php } ?>
</table>
<form action="<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/alterarfichatecnica" method="post" enctype="multipart/form-data">
	<table class="tabela"  >
	            
	            <tr>
	            	<td class="titulo_dentro">Altera&ccedil;&atilde;o da Ficha T&eacute;cnica</td>
	            </tr>
	            <tr>
	            	<td >*Altera&ccedil;&atilde;o da Ficha T&eacute;cnica (detalhada)<br /><textarea name="alteracaoFicha" id="alteracaoFicha" cols="70"  rows="10" maxlength="600"></textarea></td>
	            </tr>
	            <tr>
	            	<td >*Justificativa<br /><textarea name="justificativa" id="justificativa" cols="70"  rows="10" maxlength="600"></textarea></td>
	            </tr>
	             <tr>
	            	<td >*Anexos<br /><input type="file" name="anexo" />&nbsp;&nbsp;&nbsp;&nbsp;
	            	<input type="submit" name="nome" value="Anexar Arquivo" /></td>
	            </tr>
	            
		
	            <tr>
	            	<td ><input type="button" title=" " class="btn_alterar" />
	            	<input type="button" title="Cancelar" class="btn_cancelar" onclick="redirecionar('<?php echo $this->baseUrl(); ?>/solicitaralteracaoprojeto/index')"/></td>
	            	 <?php foreach ($this->resposta as $resposta) {?>
	            	 <input type="hidden" name="pron" value="<?php echo $this->escape($resposta->idPronac); ?>">
	            	 <input type="hidden" name="prop" value="<?php echo $this->escape($resposta->CgcCpf); ?>">
	            	 <?php } ?>
	            </tr>
	            <tr>
	            	<td ><br>Todos os campos com * s&atilde;o obrigatórios</td>
	            </tr>	
	  </table>
</form>

</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />
