<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        window.print();
    });
</script>

<style type="text/css" media="all">
    body {
        margin:0;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        color:#000;
        line-height:14pt;
    }
    a:link, a:active, a:visited {
        text-decoration:underline;
    }
    a:hover {
        text-decoration:none;
    }
    .tabela { /* tamanho de tabelas com registros */
        margin:10px auto;
        width:97%;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
        border-spacing: 1px;
        empty-cells: show;
    }
    table td {
        background:#fff;
        padding:4px;
        color:auto;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table tr.destacar td, table td.destacar {
        background:#e2e2e2;
        font:12px "Trebuchet MS", Georgia, "Times New Roman", Times, serif;
        border: 1px #999 solid;
    }
    table th {
        background:#cdcdcd;
        padding:4px;
        text-transform:uppercase;
        font-size:11px;
        border: 1px #999 solid;
        color: #000;
    }
    #brasao{
        width : 85px;
        height: 86px;
    }
    legend{
        font-size:13px;
        font-weight: bold;
    }
    .btn_imprimir{
        border-top:1px solid #efefef;
        border-left:1px solid #efefef;
        border-right:1px solid #aaa;
        border-bottom:1px solid #aaa;
        margin:0 5px 0 0;
        width:20px;
        height:21px;
        text-align:center;
        cursor:pointer;
        background:url('<?php echo $this->baseUrl(); ?>/public/img/buttons/imprimir.gif') center center no-repeat;
    }
    .btn_imprimir:hover{
        background-color:#fff;
        border-top:1px solid #aaa;
        border-left:1px solid #aaa;
        border-right:1px solid #efefef;
        border-bottom:1px solid #efefef;
    }
    .paginaA4{
        width:auto;
        margin: 1.111cm 1cm 1cm 1.005cm;
        page-break-after: always;
    }
    .TituloMinC{
        font-size: 14px;
        text-transform: uppercase;
        font-weight: bold;
    }
    .SubTituloMinC{
        font-size: 12px;
        text-transform: uppercase;
    }
    .TituloDoDocumento{
        font-size: 12px;
        font-weight: bold;
        text-transform: uppercase;
    }
    .DataDoDocumento{
        font-size: 10px;
    }
    .QntdRegistros{
        font-size: 12px;
    }
</style>

<?php
    $data = date('d/m/Y');
    $data = explode('/',$data);
    $dia  = $data[0];
    $mes  = $data[1];
    $ano  = $data[2];

    switch($mes) {
        case '01': $mes = "janeiro";
            break;
        case '02': $mes = "fevereiro";
            break;
        case '03': $mes = "mar&ccedil;o";
            break;
        case '04': $mes = "abril";
            break;
        case '05': $mes = "maio";
            break;
        case '06': $mes = "junho";
            break;
        case '07': $mes = "julho";
            break;
        case '08': $mes = "agosto";
            break;
        case '09': $mes = "setembro";
            break;
        case '10': $mes = "outubro";
            break;
        case '11': $mes = "novembro";
            break;
        case '12': $mes = "dezembro";
            break;
    }
    $dataEscrita = $dia.' de '.$mes.' de '.$ano;

?>

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div class="paginaA4">
    <div align="center">
        <img id="brasao" src="<?php echo $this->baseUrl(); ?>/public/img/brasaoArmas.jpg" alt="Minist&eacute;rio da Cultura"/>
        <br clear="all" /><span class="TituloMinC">Minist&eacute;rio da Cultura</span>
        <br clear="all" /><span class="SubTituloMinC">Secretaria de Fomento e Incentivo &agrave; Cultura</span>
        <br clear="all" /><span class="SubTituloMinC">Diretoria de Incentivo &agrave; Cultura</span>
        <br clear="all" /><span class="SubTituloMinC">Coordena&ccedil;&atilde;o-Geral de An&aacute;lise de Projetos de Incentivos Fiscais</span>
        <br clear="all" /><span class="SubTituloMinC">Coordena&ccedil;&atilde;o de Aprova&ccedil;&atilde;o de Projetos</span>
        <!--<br clear="all" /><span class="DataDoDocumento">Data da impress&atilde;o: <?php //echo date('d/m/Y - H:i:s'); ?></span>-->
    </div>
    
    <br clear="all" />
    
    <?php foreach ($this->arrayGrupos as $g){ ?>
        <?php if ($g->gru_codigo == $this->grupoAtivo && $g->uog_orgao == $this->orgaoAtivo){ $siglaOrgao = $g->org_siglaautorizado; } ?>
    <?php } ?>

    <div>
        <p>Despacho nº _____________/<?php echo date('Y'); ?>-<?php echo $siglaOrgao; ?></p>
        <p align="right">Bras&iacute;lia, <?php echo $dataEscrita; ?></p>
        <p>&agrave; <span style="font-weight: bold;">Coordena&ccedil;&atilde;o-Geral de Acompanhamento e Avalia&ccedil;&atilde;o</span>.</p>
        <p>
            <span style="font-weight: bold;">Projeto:</span> <?php echo $this->dadosProjeto['NomeProjeto']; ?><br />
            <span style="font-weight: bold;">Proponente:</span> <?php echo $this->dadosProjeto['Proponente']; ?><br />
            <span style="font-weight: bold;">Processo:</span> <?php echo $this->dadosProjeto['Processo']; ?><br />
            <span style="font-weight: bold;">Pronac:</span> <?php echo $this->dadosProjeto['NrProjeto']; ?><br />
            <span style="font-weight: bold;">Assunto:</span> An&aacute;lise documental
        </p>
        <br clear="all" />
        <p style="margin-left: 2em;">Senhor(a)  Coordenador(a),</p>
        <br clear="all" />
        <p style="text-align: justify;">1. Considerando o resultado da avalia&ccedil;&atilde;o t&eacute;cnica realizada pela(s) &aacute;rea(s) competente(s) e ainda da aprecia&ccedil;&atilde;o da Comiss&atilde;o Nacional de Incentivo &agrave; Cultura - CNIC, o projeto em ep&iacute;grafe foi devidamente aprovado pela Secretaria de Fomento e Incentivo &agrave; Cultura, conforme decis&atilde;o do Diretor de Incentivo &agrave; Cultura.</p>
        <br clear="all" />
        <p style="text-align: justify;">2. Desta forma, visando a publica&ccedil;&atilde;o da Portaria de Autoriza&ccedil;&atilde;o para Capta&ccedil;&atilde;o de Recursos, esta Coordena&ccedil;&atilde;o procedeu a verifica&ccedil;&atilde;o da plena instru&ccedil;&atilde;o dos autos mediante a checagem da documenta&ccedil;&atilde;o jur&iacute;dica e de regularidade fiscal, em observância ao disposto nos incisos I ou II, e inciso IV do art. 11º da Instru&ccedil;&atilde;o Normativa nº 1, de 24/06/2013, bem assim nos incisos I ou II do art. 46 desta mesma Instru&ccedil;&atilde;o e observamos que, na presente data, constam dos autos, em meio virtual, os documentos listados em espelho de documentos anexados.</p>
        <br clear="all" />
        <p style="text-align: justify;">3. Face ao resultado da an&aacute;lise documental realizada, constatamos que o projeto est&aacute; plenamente instru&iacute;do, conforme indicado no check list abaixo, resultando na necessidade de encaminhamento &agrave; Coordena&ccedil;&atilde;o-Geral de Acompanhamento e Avalia&ccedil;&atilde;o desta Secretaria para continuidade dos trâmites administrativos afetos &agrave; publica&ccedil;&atilde;o da Portaria de Autoriza&ccedil;&atilde;o para Capta&ccedil;&atilde;o de Recursos, de acordo com o disposto no art. 47 da Instru&ccedil;&atilde;o Normativa nº 1, de 24/06/2013.</p>
        
    </div>
</div>
    
<div class="paginaA4">
    <div>
        <p>
        <table class="tabela">
            <tr>
                <td>Cópia do documento legal de identifica&ccedil;&atilde;o dos dirigentes da Institui&ccedil;&atilde;o ou do proponente em caso de Pessoa F&iacute;sica, que contenha foto e assinatura, nº da Carteira de Identidade e do CPF</td>
                <td style="width: 50px;" align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Cópia da ata de elei&ccedil;&atilde;o da atual diretoria, do termo de posse de seus dirigentes, devidamente registrado, ou do ato de nomea&ccedil;&atilde;o de seus dirigentes</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Cronograma de execu&ccedil;&atilde;o atualizado, com data de in&iacute;cio e t&eacute;rmino do projeto</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Certid&atilde;o Conjunta Negativa de D&eacute;bitos relativos aos Tributos Federais e &agrave; Divida Ativa da Uni&atilde;o - CQTF</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Certificado de Regularidade do FGTS</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Certid&atilde;o Negativa de D&eacute;bitos Relativos &agrave;s Contribui&ccedil;&otilde;es Previdenci&aacute;rias e &agrave;s de Terceiros - INSS</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Espelho de regularidade do proponente junto ao Minist&eacute;rio da Cultura</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Espelho de certid&otilde;es negativas emitido pelo SALIC</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
            <tr>
                <td>Espelho de documentos anexados</td>
                <td align="center"><img src="<?php echo $this->baseUrl(); ?>/public/img/ok_16x16.png" alt="Ok"/></td>
            </tr>
        </table>
        </p>
        
        <br clear="all" />
        <p style="margin-left: 2em;">Atenciosamente,</p>
        <p style="font-size: 14px;" align="center">
            <?php echo $this->dados['agenteAdministrativoNome']; ?><br />
            <span style="font-weight: bold;"><?php echo $this->dados['agenteAdministrativoCargo']; ?></span>
        </p>
        
        <br clear="all" />
        <p style="margin-left: 2em;">De acordo. &agrave; considera&ccedil;&atilde;o da Coordenadora de Aprova&ccedil;&atilde;o de Projetos.</p>
        <p align="right">Bras&iacute;lia, <?php echo $dataEscrita; ?>.</p>
        <p style="font-size: 14px;" align="center">
            <?php echo $this->dados['chefeDivisaoNome']; ?><br />
            <span style="font-weight: bold;"><?php echo $this->dados['chefeDivisaoCargo']; ?></span>
        </p>
        
        <br clear="all" />
        <p style="margin-left: 2em;">De acordo. Encaminhar o projeto para publica&ccedil;&atilde;o.</p>
        <p align="right">Bras&iacute;lia, <?php echo $dataEscrita; ?>.</p>
        <p style="font-size: 14px;" align="center">
            <?php echo $this->dados['coordAprovacaoNome']; ?><br />
            <span style="font-weight: bold;"><?php echo $this->dados['coordAprovacaoCargo']; ?></span>
        </p>
        
<!--        [agenteAdministrativoCargo] => Agente Administrativo
    [agenteAdministrativoNome] => Rômulo Menhô Barbosa
    [chefeDivisaoCargo] => Chefe de Divis&atilde;o
    [chefeDivisaoNome] => Jefferson
    [coordAprovacaoCargo] => Coordenadora de Aprova&ccedil;&atilde;o de Projetos
    [coordAprovacaoNome] => Alessandro-->
    </div>
</div>