<?php
/**
 * Emiss&atilde;o de Parecer (N&atilde;o Acompanhar Parecer)
 * @author Equipe RUP - Politec
 * @since 12/05/2010
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.execucaofisicaprojeto
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */

echo $this->partial('inc/menu.inc.php', $this) // menu
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'areadetrabalho', 'action' => 'index')); ?>" title="Ir para An&aacute;lise do Membro da Comiss&atilde;o">An&aacute;lise do Membro da Comiss&atilde;o</a></li>
		<li class="last">Emitir Parecer - N&atilde;o acompanhar parecer</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Emitir Parecer - N&atilde;o acompanhar parecer <span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">



	<?php echo $this->partial('inc/menu_abas.inc.php', $this) // menu ?>
	
	<!-- ========== INÍCIO TÍTULO P&aacute;GINA ========== -->
	<table class="tabela">
	
		<?php foreach ($this->pronac as $p) : ?>
		<tr>
			<th>
				<p>Emitir Parecer - N&atilde;o acompanhar parecer</p>
				<p>PRONAC: <?php echo $p->IdPRONAC; ?> - <?php echo $p->NomeProjeto; ?></p>
			</th>
		</tr>
		<?php endforeach; ?>
	
	</table>
	<!-- ========== FIM TÍTULO P&aacute;GINA ========== -->



	<!-- ========== INÍCIO FORMUL&aacute;RIO ========== -->
	<form action="<?php echo $this->url(array('controller' => 'realizaranaliseprojeto', 'action' => 'aprovarparecer')); ?>" method="post">
		<input type="hidden" name="idPlanilha" value="<?php echo $_GET['idPlanilha']; ?>" />
		<input type="hidden" name="idPronac" value="<?php echo $_GET['idPronac']; ?>" />
		<input type="hidden" name="idProduto" value="<?php echo $_GET['idProduto']; ?>" />
		<input type="hidden" name="AnoProjeto" value="<?php echo $p->AnoProjeto; ?>" />
		<input type="hidden" name="Sequencial" value="<?php echo $p->Sequencial; ?>" />

		<input type="hidden" name="aprovacao" id="A" value="A" />
		<input type="hidden" name="aprovacao" id="I" value="I" />
		<input type="hidden" name="aprovacao" id="R" value="R" />
		<input type="hidden" name="aprovacao" id="N" value="N" />

		<table class="w1000" style="margin:auto;">
			<tr>
				<td colspan="6">
					<textarea name="justificativa" id="justificativa" cols="70" rows="10" style="width:98%; height:30%; border:0% solid #ccc;" <?php echo $this->contadorTextarea('form.justificativa', 'form.exibirContadorTextarea', 5000); ?>></textarea>
					<?php echo $this->exibirContadorTextarea('exibirContadorTextarea', 4, 5000, strlen($this->justificativa)); ?>
				</td>
			</tr>
		</table>

		<div class="centro">
			<br />
			<p>
				<input type="submit" class="btn" value=" Aprovar "  onclick="javascript:document.getElementById('I').disabled=true;document.getElementById('R').disabled=true;document.getElementById('N').disabled=true;" onkeypress="javascript:document.getElementById('I').disabled=true;document.getElementById('R').disabled=true;document.getElementById('N').disabled=true;" />
				<input type="submit" class="btn" value=" Indeferir " onclick="javascript:document.getElementById('A').disabled=true;document.getElementById('R').disabled=true;document.getElementById('N').disabled=true;" onkeypress="javascript:document.getElementById('A').disabled=true;document.getElementById('R').disabled=true;document.getElementById('N').disabled=true;" />
				<input type="submit" class="btn" value=" Diligênciar " onclick="javascript:document.getElementById('A').disabled=true;document.getElementById('I').disabled=true;document.getElementById('N').disabled=true;" onkeypress="javascript:document.getElementById('A').disabled=true;document.getElementById('I').disabled=true;document.getElementById('N').disabled=true;" />
				<input type="submit" class="btn" value=" Submeter a CNIC " onclick="javascript:document.getElementById('A').disabled=true;document.getElementById('I').disabled=true;document.getElementById('R').disabled=true;" onkeypress="javascript:document.getElementById('A').disabled=true;document.getElementById('I').disabled=true;document.getElementById('R').disabled=true;" />
			</p>
			<br />
		</div>



		<!-- ========== BOT&otilde;ES ========== -->
		<br />
		<p class="centro" style="margin-right:1%;">
			<input type="button" class="btn_p_anterior" value=" " onclick="redirecionar('<?php echo $this->url(array('controller' => 'realizaranaliseprojeto', 'action' => 'emitirparecer')); ?>?idPronac=<?php echo $_GET['idPronac']; ?>');" onkeypress="redirecionar('<?php echo $this->url(array('controller' => 'realizaranaliseprojeto', 'action' => 'emitirparecer')); ?>?idPronac=<?php echo $_GET['idPronac']; ?>');" />
			<input type="button" class="btn_imprimir" value=" " onclick="imprimir();" onkeypress="imprimir();" />
			<input type="submit" class="btn_salvar" value=" " />
		</p>
		<br />

	</form>
	<!-- ========== FIM FORMUL&aacute;RIO ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />