<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    Minist&eacute;rio da Cultura<br>
    Secretaria de Fomento e Incentivo &agrave; Cultura<br>
    Esplanada dos Minist&eacute;rios, Bloco "B"<br>
    Brasília/DF - CEP 70.068-900
</p>
<div>
    <p lang="pt-BR" align="LEFT">
    <strong>
        Comunicado nº ____/<?php echo date('Y'); ?>
    </strong>
    </p>
    <p lang="pt-BR" align="RIGHT">
        Brasília,____/____/_____.
    </p>
    <p lang="pt-BR" align="LEFT">
        &agrave;</br>
        PONTE ENTRE CULTURAS-MINAS GERAIS (PEC-MG)</br>
        Comercial - Rua - Radialista Maclerevski - 1101 - C&eacute;u Azul - -</br>
        Cidade: Belo Horizonte UF: MG CEP: 31.578-500
    </p>
    <p lang="pt-BR" align="LEFT">
        Projeto: {nomeProjeto}</br>
        Processo: {processo}</br>
        Pronac: {pronac}
    </p>
    <p lang="pt-BR" align="LEFT">
        Sr(a). Proponente,
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        1. No exercício das competências legalmente atribuídas ao Minist&eacute;rio da Cultura e nos termos do Par&aacute;grafo único do artigo 70 e do Inciso II do artigo 74 da
        Constitui&ccedil;&atilde;o Federal, conjugado com as determina&ccedil;&otilde;es da Lei nº 8.313/1991 e outras regulamenta&ccedil;&otilde;es específicas, comunicamos que a an&aacute;lise da Presta&ccedil;&atilde;o de
        Contas do projeto em referência foi concluída e <strong>REPROVADA</strong>, tornando o(a) proponente <strong>INABILITADO(A)</strong>, por este Minist&eacute;rio,
        conforme art. 97 da in MinC nº 01/2013.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        2. Informamos que est&atilde;o disponíveis para consulta no Sistema de Apoio &agrave;s Leis de Incentivo &agrave; Cultura (SalicWeb) o Relatório de Execu&ccedil;&atilde;o quanto ao
        cumprimento do objeto e alcance dos objetivos, a Avalia&ccedil;&atilde;o de Presta&ccedil;&atilde;o de Contas quanto aos aspectos financeiros e o Laudo de Reprova&ccedil;&atilde;o sobre a Presta&ccedil;&atilde;o
        de Contas Final do projeto em referência.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        <a name="OLE_LINK1"></a>
        3. Dessa forma, solicitamos efetuar o recolhimento dos recursos impugnados ao Fundo Nacional da Cultura - FNC, no prazo m&aacute;ximo de 30 (trinta) dias, a
        contar do recebimento deste, corrigidos conforme artigo 91 da in MinC 01/2013, pelo índice da Caderneta de Poupan&ccedil;a, de acordo com o Demonstrativo de
        C&aacute;lculo anexo, seguindo as instru&ccedil;&otilde;es abaixo:
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        - Acessar o sítio da Secretaria de Tesouro Nacional do Minist&eacute;rio da Fazenda - STN/MF (www.stn.fazenda.gov.br)</br>
        - Selecionar a op&ccedil;&atilde;o SIAFI /GRU - Guia de Recolhimento da Uni&atilde;o/GRU Simples;</br>
        - Preencher os seguintes campos da GRU:</br>
        . Unidade Favorecida: informar a Unidade Gestora (340001) e Gest&atilde;o (00001);</br>
        . Número de Referência da GRU: informar o número do PRONAC do projeto a que se refere &agrave; devolu&ccedil;&atilde;o;</br>
        . Código de recolhimento: informar o código 20082-4;</br>
        . Dados do contribuinte/proponente: informar o CNPJ ou CPF do proponente e o respectivo nome;</br>
        - Imprimir e efetuar o pagamento da guia no Banco do Brasil S/A.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        4. O comprovante de devolu&ccedil;&atilde;o (Guia de Recolhimento da Uni&atilde;o - GRU), dever&aacute; ser remetido para os seguintes e-mails:
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        5. Consoante art. 101 da in MinC nº 01/2013, o recolhimento ao FNC dos recursos irregularmente aplicados e apurados em presta&ccedil;&atilde;o de contas reverte o ato de
        reprova&ccedil;&atilde;o e a inabilita&ccedil;&atilde;o prevista no art. 97 desta Instru&ccedil;&atilde;o Normativa, desde que tais san&ccedil;&otilde;es n&atilde;o tenham decorrido de outras irregularidades.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        6. Com vistas a assegurar o direito ao contraditório e a ampla defesa desta decis&atilde;o administrativa, conforme artigo 59 da Lei 9.784, o prazo para a
        interposi&ccedil;&atilde;o de recurso &eacute; de 10 (dez) dias, consoante artigo 94 da in 01/2013, a contar do recebimento deste.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        7. A documenta&ccedil;&atilde;o referente ao recurso administrativo dever&aacute; ser encaminhada para o seguinte endere&ccedil;o: Minist&eacute;rio da Cultura - Secretaria de Fomento e
        Incentivo &agrave; Cultura - Diretoria de Incentivo &agrave; Cultura - Coordena&ccedil;&atilde;o-Geral de Presta&ccedil;&atilde;o de Contas - Esplanada dos Minist&eacute;rios, Bloco "B" - Protocolo Geral
        - Brasília/DF - CEP: 70068-900.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        8. Os recursos impetrados dentro do prazo descrito no item 6 deste comunicado, que forem providos, ensejar&atilde;o na aprova&ccedil;&atilde;o da presta&ccedil;&atilde;o de contas e na
        conseqüente habilita&ccedil;&atilde;o do proponente junto a este Minist&eacute;rio.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        9. Em tempo, n&atilde;o ser&atilde;o conhecidos os recursos apresentados fora do prazo legal, bem como o n&atilde;o cumprimento das recomenda&ccedil;&otilde;es expostas acima implicar&aacute; na
        instaura&ccedil;&atilde;o de Tomada de Contas Especial - TCE, junto ao Tribunal de Contas da Uni&atilde;o-TCU, com vistas &agrave; recomposi&ccedil;&atilde;o do Er&aacute;rio e tamb&eacute;m na inscri&ccedil;&atilde;o no
        Cadastro Informativo dos cr&eacute;ditos n&atilde;o quitados de órg&atilde;os e entidades federais - CADIN.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        10. Por fim, colocamo-nos &agrave; disposi&ccedil;&atilde;o para quaisquer dúvidas a respeito do assunto por meio do telefone (61) 2024-2090.
    </p>
    <p lang="pt-BR">
        Atenciosamente,
    </p>
    <h1 lang="pt-BR" align="CENTER">
    </h1>
    <h1 lang="pt-BR" align="CENTER">
    </h1>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorIncentivoACultura}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura Substituto(a)
    </p>
</div>