<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINIST&eacute;RIO DA CULTURA<br>
    Secretaria de Fomento e Incentivo &agrave; Cultura<br>
    Diretoria de Incentivo &agrave; Cultura<br>
    Coordena&ccedil;&atilde;o-Geral de Presta&ccedil;&atilde;o de Contas<br>
    Esplanada dos Minist&eacute;rios, Bloco "B" - Brasília/DF - CEP: 70.068-900
</p>
<div>
    <p lang="pt-BR" align="JUSTIFY">
    <strong>Laudo Final sobre a Presta&ccedil;&atilde;o de Contas nº ____/<?php echo date('Y'); ?>.</strong>
    </p>
    <p>
        Projeto: {nomeProjeto} <br>
        Proponente: {nomeProponente} <br>
        Processo: {processo} <br>
        Pronac: {pronac}
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        1. Conforme as determina&ccedil;&otilde;es previstas no Par&aacute;grafo único do artigo 70 e no inciso II da Constitui&ccedil;&atilde;o Federal, conjugados com as determina&ccedil;&otilde;es da Lei nº
        8.313/1991 e outras regulamenta&ccedil;&otilde;es específicas, esta Coordena&ccedil;&atilde;o-Geral realizou a an&aacute;lise sobre a execu&ccedil;&atilde;o financeira do projeto acima identificado.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        2. Após comprovada a incorreta aplica&ccedil;&atilde;o dos recursos públicos, conforme demonstra a Avalia&ccedil;&atilde;o da Presta&ccedil;&atilde;o de Contas emitida por esta Coordena&ccedil;&atilde;o-Geral de
        Presta&ccedil;&atilde;o de Contas/CGEPC/DIC/SEFIC/MinC, a gest&atilde;o empreendida no presente projeto cultural foi qualificada como <strong>IRREGULAR</strong>.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        3. Pelo exposto, prop&otilde;e-se o encaminhamento do presente Laudo ao Senhor Secret&aacute;rio de Fomento e Incentivo &agrave; Cultura com sugest&atilde;o de    <strong>REPROVA&ccedil;&atilde;O DA PRESTA&ccedil;&atilde;O DE CONTAS</strong> e a <strong>INABILITA&ccedil;&atilde;O DO(A) PROPONENTE</strong>. Após a decis&atilde;o final, dever&atilde;o ser atualizadas as
        informa&ccedil;&otilde;es no sistema SalicWeb e encaminhado comunicado ao proponente, quantificando o dano ao er&aacute;rio e solicitando a devolu&ccedil;&atilde;o dos recursos impugnados
        corrigidos pelo índice da Caderneta de Poupan&ccedil;a, conforme artigo 91 da in nº 01/2013.
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        Respeitosamente,
    </p>
    <p lang="pt-BR" align="RIGHT">
        ___/ ___/ ____.
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorIncentivoFiscal}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Coordenador(a) de Incentivos Fiscais e Apoio T&eacute;cnico
    </p>
    <p lang="pt-BR" align="JUSTIFY">
    De acordo com o presente Laudo, proponho o encaminhamento dos autos para o(a) Sr(a). Diretor(a) de Incentivo &agrave; Cultura com sugest&atilde;o de    <strong>REPROVA&ccedil;&atilde;O DA PRESTA&ccedil;&atilde;O DE CONTAS </strong>e <strong>INABILITA&ccedil;&atilde;O</strong> do(a) proponente.
    </p>
    <p lang="pt-BR" align="RIGHT">
        ___/ ___/ ____.
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorPrestacaoDeContas}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Coordenador(a) Geral de Presta&ccedil;&atilde;o de Contas
    </p>
    <p lang="pt-BR" align="JUSTIFY">
    De acordo com o presente Laudo, proponho o encaminhamento dos autos para o(a) Sr(a). Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura Substituto(a) com sugest&atilde;o de    <strong>REPROVA&ccedil;&atilde;O DA PRESTA&ccedil;&atilde;O DE CONTAS </strong>e <strong>INABILITA&ccedil;&atilde;O</strong> do(a) proponente.
    </p>
    <p lang="pt-BR" align="RIGHT">
        ___/ ___/ ____.
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{diretorIncentivoACultura}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Diretor(a) de Incentivo &agrave; Cultura
    </p>
    <p lang="pt-BR" align="JUSTIFY">
        De acordo com o presente Laudo, <strong>REPROVO A PRESTA&ccedil;&atilde;O DE CONTAS </strong>do projeto epigrafado e defiro a <strong>INABILITA&ccedil;&atilde;O</strong> do(a)
        proponente. Comunique-se e publique-se.
    </p>
    <p lang="pt-BR" align="RIGHT">
        ___/ ___/ ____.
    </p>
    <p lang="pt-BR" align="CENTER">
        <strong>{coordenadorIncentivoACultura}</strong>
    </p>
    <p lang="pt-BR" align="CENTER">
        Secret&aacute;rio(a) de Fomento e Incentivo &agrave; Cultura Substituto(a)
    </p>
</div>