<?php
/**
 * Publica&ccedil;&atilde;o no DOU
 * @author Equipe RUP - Politec
 * @since 11/08/2010
 * @version 1.0
 * @package application
 * @subpackage application.controller.PublicacaoDou
 * @link http://www.cultura.gov.br
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 */
	
?>
	
	<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
	<div id="breadcrumb">
		<ul>
			<li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
			<li><a href="<?php echo $this->url(array('controller' => 'publicacaodou', 'action' => 'index')); ?>" title="Ir para P&aacute;gina Inicial da Publica&ccedil;&atilde;o no Di&aacute;rio Oficial da Uni&atilde;o">Publica&ccedil;&atilde;o no Di&aacute;rio Oficial da Uni&atilde;o</a></li>
			<li class="last">P&aacute;gina Inicial para Publica&ccedil;&atilde;o no DOU</li>
		</ul>
	</div>
	<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
	
	
	
	<!-- ========== INÍCIO TÍTULO ========== -->
	<div id="titulo">
		<div>P&aacute;gina Inicial para Publica&ccedil;&atilde;o no DOU<span>ID #23A</span> <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
	</div>
	<!-- ========== FIM TÍTULO ========== -->
	
	
	
	<!-- ========== INÍCIO CONTEÚDO ========== -->
	<div id="conteudo">
	
	
<table class="tabela">
<tr> <th>PORTARIA</th></tr>
</table>

<p class = "centro">ATO PORTARIA N.º XXXX, de XX (data atual) DE XX (mês atual) de XXXX (ano atual).</p> <br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;O SECRET&aacute;RIO DE FOMENTO E INCENTIVO &agrave; CULTURA, no uso das atribui&ccedil;&otilde;es legais, que lhe confere a Portaria nº 17 de 12 de janeiro  de 2010 e o art. 4º da Portaria nº 120, de 29 de nar&ccedil;o de 2010, RESOLVE :
	<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art. 1.º - Aprovar projetos culturais, relacionados nos anexos I e II &agrave; esta Portaria, para os quais os proponentes ficam autorizados a captar recursos, mediante doa&ccedil;&otilde;es ou patroc&iacute;nios, na forma prevista, respectivamente, no § 1º do artigo 18 e no artigo 26 da lei n.º 8.313, de 23 de novembro de 1999.
<br>	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Art. 2.º - Esta portaria entre em vigor na data de sua publica&ccedil;&atilde;o.
<br></br>
		<p class = "centro">		##ASS (nome do ator selecionado)</p>




</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />