<?php
/**
 * Parecer Consolidado
 * @author Equipe RUP - Politec
 * @since 12/05/2010
 * @version 1.0
 * @package application
 * @subpackage application.view.realizaranaliseprojeto
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<?php echo $this->partial('inc/menu_abas.inc.php', $this) // menu ?>

<!-- ========== Inicio Parecer Consolidado ========== -->

<!-- ========== Inicio Parecer Consolidado ========== -->

<!-- ========== Inicio Parecer Consolidado ========== -->

                            <table class="tabela">
                                <tr>
                                    <th>PRONAC</th>
                                    <th colspan="2">Nome do Projeto</th>
                                </tr>
                                <tr>
                                <tr>
                                    <td><?php echo $this->escape($this->ResultRealizarAnaliseProjeto[0]->pronac); ?></td>
                                    <td colspan="2"><?php echo $this->escape($this->ResultRealizarAnaliseProjeto[0]->NomeProjeto); ?></td>
                                </tr>
                                </tr>
                                <tr>
                                    <th>Enquadramento</th>
                                    <th>Parecer Favor&aacute;vel?</th>
                                    <th>Sugerido</th>
                                </tr>
                                <tr>
                                    <td><?php echo $this->escape($this->enquadramento); ?></td>
                                    <td>
                                    	<?php echo $this->escape($this->parecerfavoravel); ?>
                                    	<input type="hidden" name="verificarParecerFavoravel" id="verificarParecerFavoravel" value="<?php echo $this->escape($this->parecerfavoravel); ?>" />
                                    </td>
                                    <td>
                    <?php
                            if (isset($this->totalsugerido)) {
                                echo $this->escape($this->formatarReal($this->totalsugerido));
                            }
                            else
                                echo 'R$ 0,00';
                            ;
                    ?>
                        </td>
                    </tr>
                </table>
                <table class="tabela">
                    <tr>
                        <th colspan="2">Memória de C&aacute;lculo</th>
                    </tr>
                    <tr>
                        <td>Valor Solicitado(A)</td>
                        <td>
                    <?php
                            if (isset($this->fontesincentivo)) {
                                echo $this->escape($this->formatarReal($this->fontesincentivo));
                            }
                            else
                                echo 'R$ 0,00';
                            ;
                    ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Valor de outras fontes(B)</td>
                        <td>
                    <?php
                            if (isset($this->outrasfontes)) {
                                echo $this->escape($this->formatarReal($this->outrasfontes));
                            }
                            else
                                echo 'R$ 0,00';
                            ; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Valor da Proposta(C=A+B)</td>
                        <td>
                    <?php
                            if (isset($this->valorproposta)) {
                                echo $this->escape($this->formatarReal($this->valorproposta));
                            }
                            else
                                echo 'R$ 0,00';
                            ;
                    ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Valor do componente da comiss&atilde;o</td>
                        <td>
                    <?php
                            if (isset($this->totalsugerido)) {
                                echo $this->escape($this->formatarReal($this->totalsugerido));
                            }
                            else
                                echo 'R$ 0,00';
                            ;
                    ?>
                        </td>
                    </tr>
                </table>
                <table class="tabela">
                    <tr>
                        <th colspan="6">Outras Informa&ccedil;&otilde;es</th>
                    </tr>
                    <tr>
                        <th>Produto</th>
                        <th>Enquadramento</th>
                        <th>Artigo 27 - Inciso I </th>
                        <th>Artigo 27 - II</th>
                        <th>Artigo 27 - III</th>
                        <th>Artigo 27 - IV</th>
                    </tr>
            <?php
                            foreach ($this->ResultProduto as $produto) {
            ?>
                                <tr>
                                    <td><?php echo $this->escape($produto->produto); ?></td>
                <?php
                                if ($produto->stArtigo18 == 1)
                                    print "<td>Artigo 18</td>";
                                if ($produto->stArtigo26 == 1)
                                    echo "<td>Artigo 26</td>";
                                if ($produto->stArtigo27 == 1) {
                                    if ($produto->stIncisoArtigo27_I == 1)
                                        echo "<td>SIM</td>"; else
                                        echo "<td>NAO</td>";
                                    if ($produto->stIncisoArtigo27_II == 1)
                                        echo "<td>SIM</td>"; else
                                        echo "<td>N&atilde;O</td>";

                                    if ($produto->stIncisoArtigo27_III == 1)
                                        echo "<td>SIM</td>"; else
                                        echo "<td>NAO</td>";


                                    if ($produto->stIncisoArtigo27_IV == 1)
                                        echo "<td>SIM</td>"; else
                                        echo "<td>NAO</td>";
                                }
                                else {
                                    echo "  <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    ";
                                }
                            }
                ?>
                    </table>
        <!-- ========== Fim Parecer Consolidado ========== -->
        <table class="tabela">
            <tr>
                <th>Parecer T&eacute;cnico</th>
            </tr>
            <tr>
                <td>
            <?php
            echo "<br><strong>Parecer T&eacute;cnico Parecerista</strong><br/>";
                echo $this->parecerTecnico;
            echo "<br><strong>Parecer T&eacute;cnico Componente da Comiss&atilde;o</strong><br/>";
                echo $this->parecerComponente;
            ?>

        </td>
    </tr>
</table>


<!-- ========== BOT&otilde;ES ========== -->
<br />
