<?php
/**
 * Busca PRONAC (Acesso: PROPONENTES)
 * @author Equipe RUP - Politec
 * @since 28/04/2010
 * @version 1.0
 * @package application
 * @subpackage application.view.scripts.execucaofisicadoprojeto
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="last">Comprova&ccedil;&atilde;o de Execu&ccedil;&atilde;o Física do Projeto</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Comprova&ccedil;&atilde;o de Execu&ccedil;&atilde;o Física do Projeto</div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

	<!-- ========== FORMUL&aacute;RIO PARA BUSCAR PRONAC ========== -->
	<form class="form" name="formBuscar" id="formBuscar" method="post" 
		action="<?php echo $this->url(array('controller' => 'execucaofisicadoprojeto', 'action' => 'buscarpronac')); ?>">

		<table class="tabela_busca">
			<tr>
				<th colspan="2">COMPROVA&ccedil;&atilde;O DE EXECU&ccedil;&atilde;O FÍSICA DO PROJETO</th>
			<tr>
			<tr>
				<th class="titulo_campo"><label for="pronac">Nº PRONAC:</label></th>
				<td>
					<div class="left"></div>
					<input class="input w150" type="text" name="pronac" id="pronac" maxlength="20" 
						onkeyup="mascara(this, format_num);" onmouseup=" " 
						onclick="limpar_campo(this, 'Digite o nº do PRONAC!');" onkeypress=" " 
						onblur="restaurar_campo(this, 'Digite o nº do PRONAC!');" onmouseout=" "
						value="<?php echo isset($_GET['pronac'])? $_GET['pronac']: 'Digite o nº do PRONAC!';?>"
                                        />
					<?php echo $this->botaoPesquisar('formBuscar'); ?>
				</td>
			</tr>
		</table>

	</form>
	<!-- ========== FIM FORMUL&aacute;RIO DE BUSCA PRONAC ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />