<?php
/**
 * Visualiza&ccedil;&atilde;o de comprovantes (Acesso: PROPONENTES)
 * @author Equipe RUP - Politec
 * @since 28/04/2010
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.execucaofisicadoprojeto
 * @copyright © 2010 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://www.cultura.gov.br
 */
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li class="last">Comprova&ccedil;&atilde;o de Execu&ccedil;&atilde;o F&iacute;sica do Projeto</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
	<div>Comprova&ccedil;&atilde;o de Execu&ccedil;&atilde;o F&iacute;sica do Projeto <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">



	<!-- ========== INÍCIO VISUALIZA&ccedil;&atilde;O DE COMPROVANTE ========== -->
	<table class="tabela" colspan="2" class="titulo_tabela">
	
		<?php foreach ($this->buscarPronac as $p): ?>
		<tr class="titulo_tabela">
			<th class="centro" colspan="2">
				<p><strong>PRONAC: <?php echo $p->pronac; ?></strong></p>
				<p><strong>PROJETO: <?php echo $p->NomeProjeto; ?></strong></p>
			</th>
		</tr>
		<?php endforeach; ?>
	
	
	
		<?php foreach ($this->buscarDoc as $d): ?>
		<tr>
			<th class="centro" width="20%">TIPO DE DOCUMENTO</th>
			<td class="esquerda"><?php echo $d->dsTipoDocumento; ?></td>
		</tr>
		<tr>
			<th class="centro">TÍTULO</th>
			<td class="esquerda"><?php echo $d->nmComprovante; ?></td>
		</tr>
		<tr>
			<th class="centro">DESCRI&ccedil;&atilde;O</th>
			<td class="esquerda"><?php echo $d->dsComprovante; ?></td>
		</tr>
		<tr>
			<th class="centro">ARQUIVO</th>
			<td class="esquerda"><a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')); ?>?id=<?php echo $d->idArquivo; ?>"><?php echo $d->nmArquivo; ?></a></td>
		</tr>
	
		<?php if ($d->stParecerComprovante == 'CS') : // 'Comprovante Substitu&iacute;do' ?>
		<tr>
			<th class="centro">JUSTIFICATIVA PARA A ALTERA&ccedil;&atilde;O</th>
			<td class="esquerda"><?php echo $d->dsJustificativaAlteracao; ?></td>
		</tr>
		<tr>
			<th class="centro">PARECER T&eacute;CNICO</th>
			<td class="esquerda"><?php echo $d->dsJustificativaCoordenador; ?></td>
		</tr>
		<?php endif; ?>
	
		<?php if ($d->stParecerComprovante == 'AD' || $d->stParecerComprovante == 'AI') : // 'Comprovante Deferido - Indeferido' ?>
		<tr>
			<th class="centro">JUSTIFICATIVA DE ALTERA&ccedil;&atilde;O</th>
			<td class="esquerda"><?php echo $d->dsJustificativaAlteracao; ?></td>
		</tr>
		<tr>
			<td class="centro" colspan="2">
				<?php if ($d->stParecerComprovante == 'AD') : // 'Comprovante Deferido' ?>
				<p>Substitui&ccedil;&atilde;o aceita (deferido)</p>
				<?php endif; ?>
				<?php if ($d->stParecerComprovante == 'AI') : // 'Comprovante Indeferido' ?>
				<p>Substitui&ccedil;&atilde;o n&atilde;o aceita (indeferido)</p>
				<?php endif; ?>
				<br />
				<p>Justificativa: <?php echo $d->dsJustificativaCoordenador; ?></p>
			</td>
		</tr>
		<?php endif; ?>
	
		<?php endforeach; ?>
	
	
	
	</table>
	
	
	
	<!-- ========== BOT&otilde;ES VOLTAR E ETC ========== -->
	<table class="tabela">
		<tr>
			<td>
				<div class="float_left">
					<input type="button" class="btn_voltar" title=" P&aacute;gina Anterior "
						onkeypress=" " 
						onclick="voltar();" />
				</div>			
			</td>
		</tr>
	</table>
	
	<!-- ========== FIM VISUALIZA&ccedil;&atilde;O DE COMPROVANTE ========== -->



</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />