<?php if($this->idPerfil == 1111){ ?>
<table class="tabela">
    <tr>
        <td><input type="button" class="btn_incluir" id="adicionarPlanosDeDivulgacao" title="Adicionar Planos de Divulga&ccedil;&atilde;o" /></td>
    </tr>
</table>
<?php } ?>

<table class="tabela">
    <tr>
        <th>Pe&ccedil;a</th>
        <th>Ve&iacute;culo</th>
        <th style="width: 150px;">Solicita&ccedil;&atilde;o Proponente</th>
        <?php if(in_array($this->siEncaminhamento, array(4,5,6,7,9,10))){ ?>
        <th style="width: 150px;">Avalia&ccedil;&atilde;o T&eacute;cnica</th>
        <?php } ?>
        
        <?php if(in_array($this->siEncaminhamento, array(7,9))){ ?>
        <th style="width: 150px;">Avalia&ccedil;&atilde;o Conselheiro</th>
        <?php } ?>
    </tr>
    
    <?php foreach ($this->planosDeDivulgacao as $p){
        $corLinha = '';
        switch ($p['tpSolicitacao']) {
            case 'E':
                $corLinha = 'red';
                if($this->idPerfil == 1111){
                    $corLinha = 'silver';
                }
                break;
            case 'I':
                $corLinha = 'green';
                break;
            case 'A':
                $corLinha = 'blue';
                break;
            default:
                $corLinha = '';
                break;
        }
    ?>
    <tr style="color: <?php echo $corLinha; ?> !important;">
        <td><?php echo $p->Peca; ?></td>
        <td><?php echo $p->Veiculo; ?></td>
        <td class="centro">
            <?php if($this->idPerfil == 1111){
                    if($p['tpSolicitacao'] == 'E'){
                        echo '<span style="margin: 10px;">Item exclu&iacute;do</span>';
                        echo '<img src="'.$this->baseUrl().'/public/img/refresh.gif" style="cursor: pointer;" class="restaurarItemPlanoDivulgacao" tipo="'.$p['tpSolicitacao'].'" idPlanoDivulgacao="'.$p['idPlanoDivulgacao'].'" title="restaurar item"/>';
                    } else {  ?>
                        <input type="button" class="btn_excluir btnExcluirPDD" idPlanoDivulgacao="<?php echo $p->idPlanoDivulgacao; ?>">
                <?php } }
                else {
                    $title = '';
                    switch ($p['tpSolicitacao']) {
                        case 'E':
                            echo 'Exclu&iacute;do';
                            $title = 'restaurar plano de divulga&ccedil;&atilde;o exclu&iacute;do';
                            break;
                        case 'I':
                            echo 'Inclu&iacute;do';
                            $title = 'recusar inclus&atilde;o de plano de divulga&ccedil;&atilde;o';
                            break;
                        case 'A':
                            echo 'Alterado';
                            $title = 'reintegrar item';
                            break;
                        default:
                            echo '';
                            break;
                        } ?>

                    <?php /*if(in_array($this->idPerfil, array(94,121)) && $p['tpSolicitacao'] != 'N'){ ?>
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/refresh.gif" style="cursor: pointer;" class="restaurarItemPlanoDivulgacao" tipo="<?php echo $p['tpSolicitacao']; ?>" idPlanoDivulgacao="<?php echo $p['idPlanoDivulgacao']; ?>" title="<?php echo $title; ?>"/>
                    <?php } ?>

                    <?php if($this->idPerfil == 118 && $p['tpSolicitacao'] != 'N' && $this->link){ ?>
                    <img src="<?php echo $this->baseUrl(); ?>/public/img/refresh.gif" style="cursor: pointer;" class="restaurarItemPlanoDivulgacao "tipo="<?php echo $p['tpSolicitacao']; ?>" idPlanoDivulgacao="<?php echo $p['idPlanoDivulgacao']; ?>" title="<?php echo $title; ?>"/>
                    <?php }*/ ?>
                <?php } ?>
        </td>
        
        <?php if(in_array($this->siEncaminhamento, array(4))){ ?>
        <td class="centro">
            <?php if($p->tpSolicitacao != 'N'){ ?>
            <select class="select_simples comboPlanoDeDivulgacao comboAvaliacao" style="width: 115px;" idpldd="<?php echo $p->idPlanoDivulgacao; ?>">
                <option value=""> - Selecione - </option>
                <option value="D" <?php echo ($p->tpAnaliseTecnica == 'D') ? 'selected="selected"' : ''; ?>>Deferir</option>
                <option value="I" <?php echo ($p->tpAnaliseTecnica == 'I') ? 'selected="selected"' : ''; ?>>Indeferir</option>
            </select>
            <?php } ?>
        </td>
        <?php } ?>
        
        <?php if(in_array($this->siEncaminhamento, array(5,6,7,9,10))){ ?>
        <td class="centro">
            <?php
                 switch ($p->tpAnaliseTecnica) {
                     case 'D':
                         echo '<span style="color: black !important;">Deferido</span>';
                         break;
                     case 'I':
                         echo '<span style="color: black !important;">Indeferido</span>';
                         break;
                     default:
                         echo '<span style="color: black !important;">-</span>';
                         break;
            } ?>
        </td>
        <?php } ?>
        
        <?php if(in_array($this->siEncaminhamento, array(7))){ ?>
        <td class="centro">
            <?php if($p->tpSolicitacao != 'N'){ ?>
            <select class="select_simples comboPlanoDeDivulgacao comboAvaliacao" style="width: 115px;" idpldd="<?php echo $p->idPlanoDivulgacao; ?>">
                <option value=""> - Selecione - </option>
                <option value="D" <?php echo ($p->tpAnaliseComissao == 'D') ? 'selected="selected"' : ''; ?>>Deferir</option>
                <option value="I" <?php echo ($p->tpAnaliseComissao == 'I') ? 'selected="selected"' : ''; ?>>Indeferir</option>
            </select>
            <?php } ?>
        </td>
        <?php } ?>
        
        <?php if(in_array($this->siEncaminhamento, array(9))){ ?>
        <td class="centro">
            <?php
                 switch ($p->tpAnaliseComissao) {
                     case 'D':
                         echo '<span style="color: black !important;">Deferido</span>';
                         break;
                     case 'I':
                         echo '<span style="color: black !important;">Indeferido</span>';
                         break;
                     default:
                         echo '<span style="color: black !important;">-</span>';
                         break;
            } ?>
        </td>
        <?php } ?>
        
    </tr>
    <?php } ?>
</table>

<div id="modalInclusaoPDD" class="sumir">
    <table class="tabela">
        <tr>
            <td class="destacar bold" style="width: 50%">Pe&ccedil;a</td>
            <td class="destacar bold" style="width: 50%">Ve&iacute;culo</td>
        </tr>
        <tr>
            <td>
                <select class="select_simples w200 obrigatoriosPlanosDeDivulgacao" name="newPeca" id="newPeca">
                    <option value=""> - Selecione - </option>
                    <?php foreach ($this->pecas as $peca){ ?>
                    <option value="<?php echo $peca->idVerificacao; ?>"><?php echo $peca->Descricao; ?></option>
                    <?php } ?>
                </select>
            </td>
            <td>
                <select class="select_simples w200 obrigatoriosPlanosDeDivulgacao" name="newVeiculo" id="newVeiculo">
                    <option value=""> - Selecione - </option>
                    <?php foreach ($this->veiculos as $veiculo){ ?>
                    <option value="<?php echo $veiculo->idVerificacao; ?>"><?php echo $veiculo->Descricao; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
    </table>
</div>

<div id="alertaPDD" class="sumir"></div>


<script type="text/javascript">
    $(document).ready(function(){
        $('#adicionarPlanosDeDivulgacao').click(function(){
            
            $("#modalInclusaoPDD").dialog({
                resizable: false,
                title: 'Inclus&atilde;o de Plano de Divulga&ccedil;&atilde;o!',
                width: 550,
                modal: true,
                buttons : {
                    'Cancelar' : function(){
                        $(this).dialog('close');
                    },
                    'Salvar' : function(){
                        var idPeca = $('#newPeca').val(),
                            idVeiculo = $('#newVeiculo').val();
                    
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'incluir-planos-de-divulgacao'), '', true); ?>?idPronac=<?php echo Seguranca::encrypt($this->idPronac); ?>',
                            data: {
                                newPeca: idPeca,
                                newVeiculo: idVeiculo
                            },
                            success: function(data){
                                $("#modalInclusaoPDD").dialog('destroy');
                                $("#modalInclusaoPDD").html('');
                                $("#modalInclusaoPDD").dialog( "widget" ).remove();
                                
                                if(!data.resposta){
                                    $("#alertaPDD").dialog("destroy");
                                    $("#alertaPDD").html(data.msg);
                                    $("#alertaPDD").dialog({
                                        resizable: false,
                                        title: 'Alerta!',
                                        width:320,
                                        modal: true,
                                        buttons : {
                                            'OK' : function(){
                                                $(this).dialog('close');
                                            }
                                        }
                                    });
                                    $('.ui-dialog-titlebar-close').remove();
                                }
                                atualizarDadosPlanosDeDivulgacao();
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('.btnExcluirPDD').click(function(){
            var idPlanoDivulgacao = $(this).attr('idPlanoDivulgacao');
                
            //ABRE O MODAL DE CONFIRMA&ccedil;&atilde;O DA A&ccedil;&atilde;O REALIZADA
            $("#alertaPDD").dialog("destroy");
            $("#alertaPDD").html('Tem certeza que deseja excluir o plano de divulga&ccedil;&atilde;o?');
            $("#alertaPDD").dialog({
                resizable: false,
                title: 'Alerta!',
                width:400,
                height:160,
                modal: true,
                buttons : {
                    'N&atilde;o' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $(this).dialog('close');
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'excluir-plano-de-divulgacao'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                            data: {
                                idPlanoDivulgacao: idPlanoDivulgacao
                            },
                            success: function(data){
                                $("#alertaPDD").dialog("destroy");
                                atualizarDadosPlanosDeDivulgacao();
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('.restaurarItemPlanoDivulgacao').click(function(){
            var idPlanoDivulgacao = $(this).attr('idPlanoDivulgacao'),
                tpAcao = $(this).attr('tipo'),
                msg = '';
                
            if(tpAcao == 'I'){
                msg = 'Tem certeza que deseja excluir o plano de divulga&ccedil;&atilde;o adicionado?';
            } else {
                msg = 'Tem certeza que deseja restaurar o plano de divulga&ccedil;&atilde;o exclu&iacute;do?';
            }
            
            $("#alertaPDD").dialog("destroy");
            $("#alertaPDD").html(msg);
            $("#alertaPDD").dialog({
                resizable: false,
                width:340,
                modal: true,
                title: 'Alerta!',
                buttons : {
                    'N&atilde;o' : function(){
                        $(this).dialog('close');
                    },
                    'Sim' : function(){
                        $(this).dialog("close");
                        $.ajax({
                            type: 'POST',
                            url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'alteracoes-tecnicas-no-plano-de-divulgacao'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                            data: {
                                idPlanoDivulgacao: idPlanoDivulgacao,
                                tpAcao: tpAcao
                            },
                            success: function(data){
                                <?php if($this->idPerfil == 1111){ ?>
                                    atualizarDadosPlanosDeDivulgacao();
                                <?php } else { ?>
                                    jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'carregar-planos-de-divulgacao-readequacoes'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>&idReadequacao=<?php echo $this->idReadequacao; ?>', '', 'planosDeDivulgacao');
                                <?php } ?>
                            },
                            dataType : 'json'
                        });
                    }
                }
            });
            $('.ui-dialog-titlebar-close').remove();
        });
        
        $('.comboPlanoDeDivulgacao').change(function(){
            var tpAcao = $(this).val(),
                idPlanoDivulgacao = $(this).attr('idpldd'),
                select = $(this);
                
            if(tpAcao != ''){
                $("#alertaPDD").dialog("destroy");
                $("#alertaPDD").html('Deseja realmente avaliar o item?');
                $("#alertaPDD").dialog({
                    resizable: false,
                    width:340,
                    modal: true,
                    title: 'Alerta!',
                    buttons : {
                        'N&atilde;o' : function(){
                            $(this).dialog('close');
                            select.val('');
                        },
                        'Sim' : function(){
                            $(this).dialog('close');
                            $.ajax({
                                type: 'POST',
                                url: '<?php echo $this->url(array('controller' => 'readequacoes', 'action' => 'alteracoes-tecnicas-no-plano-de-divulgacao'), '', true); ?>?idPronac=<?php echo $this->idPronac; ?>',
                                data: {
                                    idPlanoDivulgacao: idPlanoDivulgacao,
                                    tpAcao: tpAcao
                                },
                                success: function(data){
                                    <?php if($this->idPerfil == 1111){ ?>
                                        atualizarDadosPlanosDeDivulgacao();
                                    <?php } else { ?>
                                        jqAjaxLinkSemLoading('<?php echo $this->Url(array('controller' => 'readequacoes', 'action' => 'carregar-planos-de-divulgacao-readequacoes'), '', true) ?>?idPronac=<?php echo $this->idPronac; ?>&idReadequacao=<?php echo $this->idReadequacao; ?>', '', 'planosDeDivulgacao');
                                    <?php } ?>
                                },
                                dataType : 'json'
                            });
                        }
                    }
                });
                $('.ui-dialog-titlebar-close').remove();
            }
        });
    });
</script>