<?php
/**
 * NOME DO PROJETO: Solicita&ccedil;&atilde;o de altera&ccedil;&otilde;es no Nome do Projeto
 * @author emanuel.sampaio <emanuelonline@gmail.com>
 * @since 30/03/2012
 * @version 1.0
 * @package application
 * @subpackage application.views.scripts.readequacao
 * @copyright © 2012 - Minist&eacute;rio da Cultura - Todos os direitos reservados.
 * @link http://salic.cultura.gov.br
 */

echo $this->partial('inc/menu.inc.php', $this) // menu
// define os valores dos campos do formul&aacute;rio, se ser&aacute; lido o dado original ou o dado readequado
$NomeProjeto    = isset($this->dadosSR['nmProjeto']) && !empty($this->dadosSR['nmProjeto'])  ? $this->escape($this->dadosSR['nmProjeto']) : $this->escape($this->dadosAP['NomeProjeto']);
$Justificativa  = isset($this->pedido['dsJustificativa'])                                    ? $this->pedido['dsJustificativa']           : '';

$urlPronac = null;
$urlPronac = (isset($this->idPronac)) ? "?idPronac=".Seguranca::encrypt($this->idPronac) : "";
?>

<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->url(array('controller' => 'principalproponente', 'action' => ''), null, true); ?>" title="Ir para p&aacute;gina inicial" onclick="carregandoModal();">In&iacute;cio</a></li>
        <li class="second"><a href="<?php echo $this->url(array('controller' => 'consultardadosprojeto', 'action' => ''), null, true); ?><?php echo $urlPronac; ?>" title="Ir para In&iacute;cio" onclick="carregandoModal();">Consultar dados do Projeto</a></li>
        <li>Readequa&ccedil;&atilde;o de projeto</li>
        <li class="last">Nome do projeto</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->

<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Readequa&ccedil;&atilde;o de projeto - Nome do projeto <span class="voltar"><a href="javascript:voltar();" title="Ir para p&aacute;gina anterior">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->

<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">

    <!-- ========== INÍCIO TOPO PROJETO ========== -->
    <?php echo $this->partial('readequacao/inc/topo.inc.php', $this); ?>
    <!-- ========== FIM TOPO PROJETO ========== -->

    <!-- ========== INÍCIO FORMUL&aacute;RIO ========== -->
    <form name="formReadequacao" id="formReadequacao" action="<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'nome-projeto')); ?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="stPedidoAlteracao" id="stPedidoAlteracao" value="T" />
        <input type="hidden" name="siVerificacao" id="siVerificacao" value="0" />
        <input type="hidden" name="tpAlteracaoProjeto" id="tpAlteracaoProjeto" value="5" />
        <table class="tabela">
            <tr>
                <th>Nome do Projeto</th>
            </tr>
        </table>
        <table class="tabela">
            <tr class="destacar bold">
                <td align="center"><label for="nome">NOME DO PROJETO SOLICITADO</label></td>
            </tr>
            <tr>
                <td><input type="text" name="nome" id="nome" class="input_simples w99p" maxlength="300" value="<?php echo $NomeProjeto; ?>" /></td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="justificativa">JUSTIFICATIVA</label></td>
            </tr>
            <tr>
                <td>
                    <textarea name="justificativa" id="justificativa" cols="" rows="7" class="textarea_simples w99p"><?php echo $Justificativa; ?></textarea>
                    <span style="float: left; color: red;">Limite m&aacute;ximo de 600 caracteres</span>
                </td>
            </tr>
            <tr class="destacar bold">
                <td align="center"><label for="arquivo">ANEXOS</label></td>
            </tr>
            <tr>
                <td>
                    <div>
                        <span style="float: left; margin-right: 10px;"><input type="file" name="arquivo[]" id="arquivo" class="multi input_simples w99p" accept="pdf" /></span>
                        <span style="float: left; color: red;">Tamanho m&aacute;ximo de 5 MB</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <?php if (count($this->arquivos) > 0) : ?>
                        <?php foreach ($this->arquivos as $a) : ?>
                        <div id="excluir_arq<?php echo $a->idPedidoAlteracao . $a->idArquivo; ?>">
                            <input type="button" class="btn_exclusao btnsModReadequacao" title="Excluir Arquivo" onclick="excluir_arq_readeq('<?php echo $a->idPedidoAlteracao; ?>', '<?php echo $a->idArquivo; ?>', '<?php echo $a->nmArquivo; ?>');" />
                            <a href="<?php echo $this->url(array('controller' => 'upload', 'action' => 'abrir')) . '?id=' . $a->idArquivo; ?>" title="Abrir Arquivo"><?php echo $a->nmArquivo; ?></a>
                        </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        Nenhum arquivo encontrado!
                    <?php endif; ?>
                </td>
            </tr>
        </table>

        <table class="tabela btnsModReadequacao">
            <tr>
                <td align="center">
                    <input type="submit" name="btn_salvar" id="btn_salvar" class="btn_salvar" value=" " title="Salvar" />
                    <input type="reset" name="btn_cancelar" id="btn_cancelar" class="btn_cancelar" value=" " title="Cancelar" />
                </td>
            </tr>
        </table>
    </form>
    <!-- ========== FIM FORMUL&aacute;RIO ========== -->

    <!-- ========== INÍCIO HISTÓRICO ========== -->
    <div id="historico"></div>
    <script type="text/javascript">
        carregaDados('<?php echo $this->url(array('controller' => 'readequacao', 'action' => 'historico-nome-projeto')); ?>', 'historico');
    </script>
    <!-- ========== FIM HISTÓRICO ========== -->

</div>
<!-- ========== FIM CONTEÚDO ========== -->

<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->
<br clear="all" />