<!-- ========== INÍCIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
    <ul>
        <li class="first"><a href="<?php echo $this->baseUrl(); ?>" title="Ir para In&iacute;cio">In&iacute;cio</a></li>
        <li class="last">Manter Agentes</li>
    </ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->



<!-- ========== INÍCIO TÍTULO ========== -->
<div id="titulo">
    <div>Imprimir <span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>
<!-- ========== FIM TÍTULO ========== -->



<!-- ========== INÍCIO CONTEÚDO ========== -->
<div id="conteudo">
    <fieldset><legend>Identifica&ccedil;&atilde;o</legend>

        <tbody>
            <tr>
                <td width="604" valign="top"  colspan="12">
                    <p class="MsoNormal">Nº Projeto : 091572 - <b>FESTIVAL CARIRI DA CAN&ccedil;&atilde;O 2010</b></p>
                </td>
            </tr>
            <tr>
                <td width="604" valign="top"  colspan="12">
                    <p class="MsoNormal">Proponente: 04.776.109/0001-76 - Núcleo de Produ&ccedil;&otilde;es Culturais - NUPROC</p>
                </td>
            </tr>
            <tr>
                <td width="604" valign="top"  colspan="12">
                    <p class="MsoNormal">&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td width="121" valign="top" >
                    <p class="MsoNormal">Dt.Cadastro: &nbsp;</p>
                </td>
                <td width="113" valign="top"  colspan="4">
                    <p class="MsoNormal">UF: CE</p>
                </td>
                <td width="85" valign="top"  colspan="3">
                    <p class="MsoNormal">&aacute;rea: Música</p>
                </td>
                <td width="198" valign="top" colspan="3">
                    <p class="MsoNormal">Segmento: Música Popular</p>
                </td>
                <td width="86" valign="top" >
                    <p class="MsoNormal">Mecanismo: Mecenato</p>
                </td>
            </tr>
            <tr>
                <td width="604" valign="top"  colspan="12">
                    <p class="MsoNormal">&nbsp;</p>
                </td>
            </tr>

    </fieldset>
    <fieldset><legend>Situa&ccedil;&atilde;o do Projeto</legend>
        <tr>
            <td width="204" valign="top"  colspan="4">
                <p class="MsoNormal">Dt.Situa&ccedil;&atilde;o: 28/05/2010</p>
            </td>
            <td width="399" valign="top" colspan="8">
                <p class="MsoNormal">Situa&ccedil;&atilde;o: <b>Autorizada a capta&ccedil;&atilde;o residual dos recursos</b></p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">Providência Tomada: <b>Of&iacute;cio n. 2648/2010 - CGAA/DIC/SEFIC/MINC de 01/06/2010 - capta&ccedil;&atilde;o inferior a 20% do valor aprovado.</b></p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">&nbsp;</p>
            </td>
        </tr>

    </fieldset>
    <fieldset><legend>Dados Banc&aacute;rios</legend>
        <tr>
            <td width="304" valign="top" colspan="7">
                <p class="MsoNormal">Banco: 001</p>
            </td>
            <td width="299" valign="top"  colspan="5">
                <p class="MsoNormal">Agência: 2925-4</p>
            </td>
        </tr>
        <tr>
            <td width="304" valign="top" colspan="7">
                <p align="center" style="text-align: center;" class="MsoNormal"><b>Conta Bloqueada</b></p>
            </td>
            <td width="299" valign="top"  colspan="5">
                <p align="center" style="text-align: center;" class="MsoNormal"><b>Conta de Livre
                        Movimenta&ccedil;&atilde;o</b></p>
            </td>
        </tr>
        <tr>
            <td width="155" valign="top" colspan="2">
                <p class="MsoNormal">Nº: 1.704-02</p>
            </td>
            <td width="150" valign="top" colspan="5">
                <p class="MsoNormal">Dt.Abertura: 24/07/2009</p>
            </td>
            <td width="150" valign="top"  colspan="3">
                <p class="MsoNormal">Nº: -</p>
            </td>
            <td width="150" valign="top" colspan="2">
                <p class="MsoNormal">Dt.Abertura: &nbsp;</p>
            </td>
        </tr>
        <tr>
            <td width="302" valign="top" colspan="6">
                <p class="MsoNormal">Dt.Libera&ccedil;&atilde;o da Conta: &nbsp;</p>
            </td>
            <td width="302" valign="top" colspan="6">
                <p class="MsoNormal">Nº Documento: &nbsp;</p>
            </td>
        </tr>
        <tr>

        </tr>

    </fieldset>
    <fieldset><legend>Dados Banc&aacute;rios</legend>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p align="center" style="text-align: center;" class="MsoNormal"><b><span style="font-size: 12pt;">Localiza&ccedil;&atilde;o do Projeto</span></b></p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">Unidade: <b>SEFIC/GEAR/SACAV</b></p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">&nbsp;</p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p align="center" style="text-align: center;" class="MsoNormal"><b><span style="font-size: 12pt;">Valores</span></b></p>
            </td>
        </tr>
        <tr>
            <td width="201" valign="top" colspan="3">
                <p class="MsoNormal">Vl.Solicitado R$: <b> 557.473,00</b></p>
            </td>
            <td width="201" valign="top" colspan="6">
                <p class="MsoNormal">Vl.Aprovado R$: <b> 447.986,00</b></p>
            </td>
            <td width="201" valign="top" colspan="3">
                <p class="MsoNormal">Vl.Captado R$: <b> 50.000,00</b></p>
            </td>
        </tr>
        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">&nbsp;</p>
            </td>
        </tr>

    </fieldset>
    <fieldset><legend>Histórico de Situa&ccedil;&otilde;es do Projeto</legend>

        <tr>
            <td width="604" valign="top"  colspan="12">
                <p class="MsoNormal">
        <tbody><tr>
                <td valign="top">
                    <table cellspacing="0" cellpadding="0" bordercolor="" border="1" bgcolor="#cccccc" align="center" width="100%">
                        <tbody><tr bgcolor="#abda5d" align="center" id="tit_conSituacoesDoProjeto">
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Dt.Situa&ccedil;&atilde;o</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Situa&ccedil;&atilde;o</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Providência Tomada</b></font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);" class="">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">27/05/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o residual dos recursos</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Of&iacute;cio n. 2648/2010 - CGAA/DIC/SEFIC/MINC de 01/06/2010 - capta&ccedil;&atilde;o inferior a 20% do valor aprovado.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">27/05/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o residual dos recursos</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Projeto com captacao parcial. Situa&ccedil;&atilde;o alterada pelo sistema.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">25/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Of&iacute;cio n. 2423/2010 - CGAA/DIC/SEFIC/MINC de 19/05/2010 - reiteramos a observância da obrigatoriedade quanto &agrave;s capta&ccedil;&otilde;es nas contas banc&aacute;rias para recebimento de incentivos fiscais, conforme previsto na portaria /MinC n. 09 de 06/03/2007.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">25/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Prorroga&ccedil;&atilde;o aprovada</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">25/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Aguardando elabora&ccedil;&atilde;o de portaria de Prorroga&ccedil;&atilde;o</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Aguardando publica&ccedil;&atilde;o de portaria</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">24/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Aguardando publica&ccedil;&atilde;o de portaria de Prorroga&ccedil;&atilde;o</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Projeto analisado. Aguardando a elabora&ccedil;&atilde;o de portaria. 25/02/2010</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">31/12/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Expirado o prazo de capta&ccedil;&atilde;o total</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Situa&ccedil;&atilde;o corrigida.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">31/12/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Expirado o prazo de capta&ccedil;&atilde;o total</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Para conhecimento e manifesta&ccedil;&atilde;o quanto ao Despacho n.0114/2010 - CGAA/DIC/SEFIC/MINC de 04/02/2010 - Atera&ccedil;&atilde;o do nome do projeto.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">31/12/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Expirado o prazo de capta&ccedil;&atilde;o total</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Prorroga&ccedil;&atilde;o do prazo de capta&ccedil;&atilde;o lan&ccedil;ada. Aguarda a publica&ccedil;&atilde;o no DOU, observada a regularidade do proponente.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Abertura de conta banc&aacute;ria bloqueada em 27/07/2009</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Oficio n. 4.286/2009 - CGAA/DIC/SEFIC/MINC de 17/12/2009 - Altera&ccedil;&atilde;o da data de realiza&ccedil;&atilde;o do projeto diligenciada.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Oficio n. 4.286/2009 - CGAA/DIC/SEFIC/MINC de 17/12/2009 - Altera&ccedil;&atilde;o da data de realiza&ccedil;&atilde;o do projeto.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Autorizada a capta&ccedil;&atilde;o total dos recursos</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Projeto aprovado</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">08/07/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Aguarda Portaria II</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Projeto Analisado. Aguardando publica&ccedil;&atilde;o de portaria. Em 09/07/2009.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Encaminhado para inclus&atilde;o em portaria</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Encaminhado para inclus&atilde;o em portaria de aprova&ccedil;&atilde;o.06/07/2009.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">18/06/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">An&aacute;lise t&eacute;cnica conclu&iacute;da</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Projeto aguardando a próxima reuni&atilde;o.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">19/05/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Encaminhado para an&aacute;lise t&eacute;cnica</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Proposta transformada em projeto cultural</font></td>
                            </tr>
                        </tbody></table>
                </td>
            </tr>
    </fieldset>
</tbody>
<fieldset><legend>Tramita&ccedil;&atilde;o do Projeto</legend>
    <tr>
        <td width="604" valign="top"  colspan="12">
            <p class="MsoNormal">&nbsp;</p>
        </td>
    </tr>

    <tr>
        <td width="604" valign="top"  colspan="12">
            <p class="MsoNormal">
    <style type="text/css">
        .css_lin_over  { background-color: #EEF8DE; }
        .css_lin_break { background-color: #EEF8DE; }
    </style>
    <table cellspacing="0" cellpadding="0" border="0" width="100%" id="apl_conTramitacao">
        <tbody><tr>
                <td width="100%" valign="top">
                    <table cellspacing="0" cellpadding="0" bordercolor="" border="1" bgcolor="#cccccc" align="center" width="100%">
                        <tbody><tr bgcolor="#abda5d" align="center" id="tit_conTramitacao">
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Origem</b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Dt.Envio</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Destino</b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Dt.Recebimento</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Estado</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Despacho</b></font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/GEAR/SACAV</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/DIP</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Cadastrado</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Incluso em portaria de Aprova&ccedil;&atilde;o.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Enviado</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">09/07/2009</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Recebido</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/DIC</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Cadastrado</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Para conhecimento e manifesta&ccedil;&atilde;o quanto ao Despacho n.0114/2010 - CGAA/DIC/SEFIC/MINC de 04/02/2010 - Atera&ccedil;&atilde;o do nome do projeto.</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Enviado</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Recebido</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">08/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/GEAR/SACAV</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Cadastrado</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Em devolu&ccedil;&atilde;o após assinatura da Diretora de Incentivo &agrave; Cultura.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">08/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Enviado</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">08/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">08/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Recebido</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">10/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/DIP</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Cadastrado</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Encaminho para publica&ccedil;&atilde;o da altera&ccedil;&atilde;o de nome do projeto</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">10/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Enviado</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">10/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">10/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Recebido</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);" class="">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">12/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">SEFIC/GEAR/SACAV</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Cadastrado</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Para arquivo corrente.</font></td>
                            </tr>
                            <tr bgcolor="#f3f3f3" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);" class="">
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">12/02/2010</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Enviado</font></td>
                                <td bgcolor="" background="/Salic/_lib/img/bg-celulas.gif" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">12/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">12/02/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Recebido</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                            </tr>
                        </tbody></table>
                </td>
            </tr>
        </tbody></table>
    <script language="javascript">
    </script>

    </td>
    </tr>
</fieldset>
<tr>
    <td width="604" valign="top"  colspan="12">
        <p class="MsoNormal">&nbsp;</p>
    </td>
</tr>


<fieldset><legend>Pedido de Prorroga&ccedil;&atilde;o</legend>

    <tr>
        <td width="604" valign="top"  colspan="12">
            <p class="MsoNormal">
    <style type="text/css">
        .css_lin_over  { background-color: #EEF8DE; }
        .css_lin_break { background-color: #EEF8DE; }
    </style>
    <table cellspacing="0" cellpadding="0" border="0" width="100%" id="apl_conPedidoProrrogacao">
        <tbody><tr>
                <td width="100%" valign="top">
                    <table cellspacing="0" cellpadding="0" bordercolor="" border="1" bgcolor="#cccccc" align="center" width="100%">
                        <tbody><tr bgcolor="#abda5d" align="center" id="tit_conPedidoProrrogacao">
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Dt.Pedido
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Dt.Inicio
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Dt.Final
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Diligenciado
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Dt.Venc.Diligência
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Atendido
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Analista
                                        </b></font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);" class="">
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">05/01/2010</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">24/02/2010</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">31/12/2010</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">N</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">&nbsp;</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">S</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">M&aacute;rcio J.Oliveira</font></td>
                            </tr>
                        </tbody></table>
                </td>
            </tr>
        </tbody></table>
</fieldset>
<fieldset><legend>Capta&ccedil;&atilde;o de Recursos</legend>
    <tr>
        <td width="604" valign="top"  colspan="12">
            <p class="MsoNormal">&nbsp;</p>
        </td>
    </tr>

    <tr>
        <td width="604" valign="top"  colspan="12">
            <p class="MsoNormal">
    <style type="text/css">
        .css_lin_over  { background-color: #EEF8DE; }
        .css_lin_break { background-color: #EEF8DE; }
    </style>
    <table cellspacing="0" cellpadding="0" border="0" width="100%" id="apl_conCaptacao">
        <tbody><tr>
                <td width="100%" valign="top">
                    <table cellspacing="0" cellpadding="0" bordercolor="" border="1" bgcolor="#cccccc" align="center" width="100%">
                        <tbody style="" id="tbody_conCaptacao_1_top">    <tr>
                                <td bgcolor="#d1e4cf" align="left" colspan="5">
                                    <span align="left"><input type="image" src="/Salic/_lib/img/fld_expand.gif" onclick="document.all.b_open_conCaptacao_1.style.display = 'none'; document.all.b_close_conCaptacao_1.style.display = ''; NM_liga_tbody(1, NM_tab_conCaptacao, 'conCaptacao'); return false;" style="display: none;" id="b_open_conCaptacao_1"><input type="image" src="/Salic/_lib/img/fld_contract.gif" onclick="document.all.b_close_conCaptacao_1.style.display = 'none'; document.all.b_open_conCaptacao_1.style.display = ''; NM_apaga_tbody(1, NM_tab_conCaptacao, 'conCaptacao'); return false;" style="" id="b_close_conCaptacao_1"></span>
                                    <font size="2" face="Trebuchet MS, Georgia, Times New Roman, Times, serif" color="#333333">Incentivador : Grendene S/A</font>
                                </td>
                            </tr>
                        </tbody>    <tbody style="" id="tbody_conCaptacao_2_bot">    <tr bgcolor="#abda5d" align="center" id="tit_conCaptacao">
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Tipo de Apoio</b></font></td>
                                <td bgcolor="#abda5d" align="left" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Nr Recibo</b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>Dt.Chegada</b></font></td>
                                <td bgcolor="#abda5d" align="center" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Dt.Recibo
                                        </b></font></td>
                                <td bgcolor="#abda5d" align="right" valign="middle"><font size="2" face="Trebuchet MS, sans-serif" color="#3a7300"><b>
                                            Vl.Captado
                                        </b></font></td>
                            </tr>
                            <tr bgcolor="#ffffff" onclick="click_tr(this);" onmouseout="out_tr(this);" onmouseover="over_tr(this);" class="">
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">Patroc&iacute;nio</font></td>
                                <td bgcolor="" align="left" valign="top" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">00001</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">28/05/2010</font></td>
                                <td bgcolor="" align="center" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333">17/05/2010</font></td>
                                <td bgcolor="" align="right" valign="top" nowrap="nowrap" rowspan="1"><font size="2" face="Trebuchet MS, sans-serif" color="#333333"> 50.000,00</font></td>
                            </tr>
                            <tr>
                                <td bgcolor="#e5eee4" align="left" colspan="4"><font size="2" face="Trebuchet MS, Georgia, Times New Roman, Times, serif" color="#333333">Total por Incentivador</font></td>
                                <td bgcolor="#e5eee4" align="right" nowrap="nowrap"><font size="2" face="Trebuchet MS, Georgia, Times New Roman, Times, serif" color="#333333"> 50.000,00</font></td>
                            </tr>
                        </tbody>    <tbody><tr>
                                <td bgcolor="#a8ca65" align="left" colspan="4"><font size="3" face="Trebuchet MS, Georgia, Times New Roman, Times, serif" color="#ffffff">
                                        <b><a name="">Total Geral (1)</a></b>
                                    </font></td>
                                <td bgcolor="#a8ca65" align="right" nowrap="nowrap"><font size="3" face="Trebuchet MS, Georgia, Times New Roman, Times, serif" color="#ffffff"><b> 50.000,00</b></font></td>
                            </tr>
                        </tbody></table>
                </td>
            </tr>
        </tbody>
    </table>
</fieldset>


<tr height="0">
    <td width="121" style="border: medium none;"></td>
    <td width="34" style="border: medium none;"></td>
    <td width="47" style="border: medium none;"></td>
    <td width="3" style="border: medium none;"></td>
    <td width="30" style="border: medium none;"></td>
    <td width="68" style="border: medium none;"></td>
    <td width="3" style="border: medium none;"></td>
    <td width="15" style="border: medium none;"></td>
    <td width="83" style="border: medium none;"></td>
    <td width="52" style="border: medium none;"></td>
    <td width="64" style="border: medium none;"></td>
    <td width="90" style="border: medium none;"></td>
</tr>
</tbody>
<table>
    <tr>
        <td>
            <input id="btn_inicio" type="button" name="inicio" style="width: 88px" class="btn_inicio" />

            <input id="btn_p_anterior" type="button" name="anterior" class="btn_p_anterior" />

            <input id="btn_p_proximo" type="button" name="proxima" class="btn_p_proximo" />

            <input id=" btn_ultimo " type="button" name="ultima" class="btn_ultimo" />

            <input id=" btn_localizar " type="button" name="localizar" class="btn_localizar" />

            <input id="btn_pdf" type="button" name="pdf" class="btn_pdf" style="width: 3.3em" />

            <input id=" btn_imprimir " type="button" name="imprimir" class="btn_imprimir" onclick="return TipoImprimir();" />

            <input id=" btn_sair " type="button" name="sair" class="btn_sair" />
        </td>
    </tr>
</table>
</div>
<!-- ========== FIM CONTEÚDO ========== -->



<!-- ========== INÍCIO RODAP&eacute; DO CONTEÚDO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTEÚDO ========== -->

<br clear="all" />
